// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/openconfig/gnoi/software_bundle/software_bundle.proto

package software_bundle

import (
	types "github.com/openconfig/gnoi/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSoftwareBundlesResponse_InstallStatus int32

const (
	ListSoftwareBundlesResponse_UNSPECIFIED     ListSoftwareBundlesResponse_InstallStatus = 0
	ListSoftwareBundlesResponse_INSTALLED       ListSoftwareBundlesResponse_InstallStatus = 1
	ListSoftwareBundlesResponse_NOT_INSTALLED   ListSoftwareBundlesResponse_InstallStatus = 2
	ListSoftwareBundlesResponse_FORCE_INSTALLED ListSoftwareBundlesResponse_InstallStatus = 3
)

// Enum value maps for ListSoftwareBundlesResponse_InstallStatus.
var (
	ListSoftwareBundlesResponse_InstallStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INSTALLED",
		2: "NOT_INSTALLED",
		3: "FORCE_INSTALLED",
	}
	ListSoftwareBundlesResponse_InstallStatus_value = map[string]int32{
		"UNSPECIFIED":     0,
		"INSTALLED":       1,
		"NOT_INSTALLED":   2,
		"FORCE_INSTALLED": 3,
	}
)

func (x ListSoftwareBundlesResponse_InstallStatus) Enum() *ListSoftwareBundlesResponse_InstallStatus {
	p := new(ListSoftwareBundlesResponse_InstallStatus)
	*p = x
	return p
}

func (x ListSoftwareBundlesResponse_InstallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSoftwareBundlesResponse_InstallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[0].Descriptor()
}

func (ListSoftwareBundlesResponse_InstallStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[0]
}

func (x ListSoftwareBundlesResponse_InstallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSoftwareBundlesResponse_InstallStatus.Descriptor instead.
func (ListSoftwareBundlesResponse_InstallStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{1, 0}
}

type InstallSoftwareBundleResponse_Operation int32

const (
	InstallSoftwareBundleResponse_UNSPECIFIED       InstallSoftwareBundleResponse_Operation = 0
	InstallSoftwareBundleResponse_TRANSFER_COMPLETE InstallSoftwareBundleResponse_Operation = 1
	InstallSoftwareBundleResponse_INSTALL_COMPLETE  InstallSoftwareBundleResponse_Operation = 2
)

// Enum value maps for InstallSoftwareBundleResponse_Operation.
var (
	InstallSoftwareBundleResponse_Operation_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "TRANSFER_COMPLETE",
		2: "INSTALL_COMPLETE",
	}
	InstallSoftwareBundleResponse_Operation_value = map[string]int32{
		"UNSPECIFIED":       0,
		"TRANSFER_COMPLETE": 1,
		"INSTALL_COMPLETE":  2,
	}
)

func (x InstallSoftwareBundleResponse_Operation) Enum() *InstallSoftwareBundleResponse_Operation {
	p := new(InstallSoftwareBundleResponse_Operation)
	*p = x
	return p
}

func (x InstallSoftwareBundleResponse_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallSoftwareBundleResponse_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[1].Descriptor()
}

func (InstallSoftwareBundleResponse_Operation) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[1]
}

func (x InstallSoftwareBundleResponse_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallSoftwareBundleResponse_Operation.Descriptor instead.
func (InstallSoftwareBundleResponse_Operation) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{6, 0}
}

type InstallRequest_TrustSource int32

const (
	InstallRequest_UNSPECIFIED  InstallRequest_TrustSource = 0
	InstallRequest_IGNORE       InstallRequest_TrustSource = 1
	InstallRequest_MANUFACTURER InstallRequest_TrustSource = 2
)

// Enum value maps for InstallRequest_TrustSource.
var (
	InstallRequest_TrustSource_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "IGNORE",
		2: "MANUFACTURER",
	}
	InstallRequest_TrustSource_value = map[string]int32{
		"UNSPECIFIED":  0,
		"IGNORE":       1,
		"MANUFACTURER": 2,
	}
)

func (x InstallRequest_TrustSource) Enum() *InstallRequest_TrustSource {
	p := new(InstallRequest_TrustSource)
	*p = x
	return p
}

func (x InstallRequest_TrustSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallRequest_TrustSource) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[2].Descriptor()
}

func (InstallRequest_TrustSource) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes[2]
}

func (x InstallRequest_TrustSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallRequest_TrustSource.Descriptor instead.
func (InstallRequest_TrustSource) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{8, 0}
}

type ListSoftwareBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSoftwareBundlesRequest) Reset() {
	*x = ListSoftwareBundlesRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSoftwareBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareBundlesRequest) ProtoMessage() {}

func (x *ListSoftwareBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareBundlesRequest.ProtoReflect.Descriptor instead.
func (*ListSoftwareBundlesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{0}
}

type ListSoftwareBundlesResponse struct {
	state           protoimpl.MessageState                        `protogen:"open.v1"`
	SoftwareBundles []*ListSoftwareBundlesResponse_SoftwareBundle `protobuf:"bytes,1,rep,name=software_bundles,json=softwareBundles,proto3" json:"software_bundles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSoftwareBundlesResponse) Reset() {
	*x = ListSoftwareBundlesResponse{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSoftwareBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareBundlesResponse) ProtoMessage() {}

func (x *ListSoftwareBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareBundlesResponse.ProtoReflect.Descriptor instead.
func (*ListSoftwareBundlesResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *ListSoftwareBundlesResponse) GetSoftwareBundles() []*ListSoftwareBundlesResponse_SoftwareBundle {
	if x != nil {
		return x.SoftwareBundles
	}
	return nil
}

type FinalizeSoftwareBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSoftwareBundlesRequest) Reset() {
	*x = FinalizeSoftwareBundlesRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSoftwareBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSoftwareBundlesRequest) ProtoMessage() {}

func (x *FinalizeSoftwareBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSoftwareBundlesRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSoftwareBundlesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{2}
}

type FinalizeSoftwareBundlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSoftwareBundlesResponse) Reset() {
	*x = FinalizeSoftwareBundlesResponse{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSoftwareBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSoftwareBundlesResponse) ProtoMessage() {}

func (x *FinalizeSoftwareBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSoftwareBundlesResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSoftwareBundlesResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{3}
}

type UninstallSoftwareBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallSoftwareBundleRequest) Reset() {
	*x = UninstallSoftwareBundleRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallSoftwareBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallSoftwareBundleRequest) ProtoMessage() {}

func (x *UninstallSoftwareBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallSoftwareBundleRequest.ProtoReflect.Descriptor instead.
func (*UninstallSoftwareBundleRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{4}
}

func (x *UninstallSoftwareBundleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UninstallSoftwareBundleRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UninstallSoftwareBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallSoftwareBundleResponse) Reset() {
	*x = UninstallSoftwareBundleResponse{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallSoftwareBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallSoftwareBundleResponse) ProtoMessage() {}

func (x *UninstallSoftwareBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallSoftwareBundleResponse.ProtoReflect.Descriptor instead.
func (*UninstallSoftwareBundleResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{5}
}

type InstallSoftwareBundleResponse struct {
	state           protoimpl.MessageState                  `protogen:"open.v1"`
	Acknowledgement InstallSoftwareBundleResponse_Operation `protobuf:"varint,3,opt,name=acknowledgement,proto3,enum=gnoi.software_bundle.InstallSoftwareBundleResponse_Operation" json:"acknowledgement,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallSoftwareBundleResponse) Reset() {
	*x = InstallSoftwareBundleResponse{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSoftwareBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSoftwareBundleResponse) ProtoMessage() {}

func (x *InstallSoftwareBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSoftwareBundleResponse.ProtoReflect.Descriptor instead.
func (*InstallSoftwareBundleResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSoftwareBundleResponse) GetAcknowledgement() InstallSoftwareBundleResponse_Operation {
	if x != nil {
		return x.Acknowledgement
	}
	return InstallSoftwareBundleResponse_UNSPECIFIED
}

type InstallSoftwareBundleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*InstallSoftwareBundleRequest_TransferRequest
	//	*InstallSoftwareBundleRequest_InstallRequest
	Request       isInstallSoftwareBundleRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSoftwareBundleRequest) Reset() {
	*x = InstallSoftwareBundleRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSoftwareBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSoftwareBundleRequest) ProtoMessage() {}

func (x *InstallSoftwareBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSoftwareBundleRequest.ProtoReflect.Descriptor instead.
func (*InstallSoftwareBundleRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSoftwareBundleRequest) GetRequest() isInstallSoftwareBundleRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InstallSoftwareBundleRequest) GetTransferRequest() *TransferRequest {
	if x != nil {
		if x, ok := x.Request.(*InstallSoftwareBundleRequest_TransferRequest); ok {
			return x.TransferRequest
		}
	}
	return nil
}

func (x *InstallSoftwareBundleRequest) GetInstallRequest() *InstallRequest {
	if x != nil {
		if x, ok := x.Request.(*InstallSoftwareBundleRequest_InstallRequest); ok {
			return x.InstallRequest
		}
	}
	return nil
}

type isInstallSoftwareBundleRequest_Request interface {
	isInstallSoftwareBundleRequest_Request()
}

type InstallSoftwareBundleRequest_TransferRequest struct {
	TransferRequest *TransferRequest `protobuf:"bytes,1,opt,name=transfer_request,json=transferRequest,proto3,oneof"`
}

type InstallSoftwareBundleRequest_InstallRequest struct {
	InstallRequest *InstallRequest `protobuf:"bytes,2,opt,name=install_request,json=installRequest,proto3,oneof"`
}

func (*InstallSoftwareBundleRequest_TransferRequest) isInstallSoftwareBundleRequest_Request() {}

func (*InstallSoftwareBundleRequest_InstallRequest) isInstallSoftwareBundleRequest_Request() {}

type InstallRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SoftwareBundleName string                 `protobuf:"bytes,1,opt,name=software_bundle_name,json=softwareBundleName,proto3" json:"software_bundle_name,omitempty"`
	LoadAfterBoot      bool                   `protobuf:"varint,3,opt,name=load_after_boot,json=loadAfterBoot,proto3" json:"load_after_boot,omitempty"`
	Force              bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	// Types that are valid to be assigned to SignatureVerification:
	//
	//	*InstallRequest_Source
	//	*InstallRequest_SslProfileId
	SignatureVerification isInstallRequest_SignatureVerification `protobuf_oneof:"signature_verification"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{8}
}

func (x *InstallRequest) GetSoftwareBundleName() string {
	if x != nil {
		return x.SoftwareBundleName
	}
	return ""
}

func (x *InstallRequest) GetLoadAfterBoot() bool {
	if x != nil {
		return x.LoadAfterBoot
	}
	return false
}

func (x *InstallRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *InstallRequest) GetSignatureVerification() isInstallRequest_SignatureVerification {
	if x != nil {
		return x.SignatureVerification
	}
	return nil
}

func (x *InstallRequest) GetSource() InstallRequest_TrustSource {
	if x != nil {
		if x, ok := x.SignatureVerification.(*InstallRequest_Source); ok {
			return x.Source
		}
	}
	return InstallRequest_UNSPECIFIED
}

func (x *InstallRequest) GetSslProfileId() string {
	if x != nil {
		if x, ok := x.SignatureVerification.(*InstallRequest_SslProfileId); ok {
			return x.SslProfileId
		}
	}
	return ""
}

type isInstallRequest_SignatureVerification interface {
	isInstallRequest_SignatureVerification()
}

type InstallRequest_Source struct {
	Source InstallRequest_TrustSource `protobuf:"varint,5,opt,name=source,proto3,enum=gnoi.software_bundle.InstallRequest_TrustSource,oneof"`
}

type InstallRequest_SslProfileId struct {
	SslProfileId string `protobuf:"bytes,6,opt,name=ssl_profile_id,json=sslProfileId,proto3,oneof"`
}

func (*InstallRequest_Source) isInstallRequest_SignatureVerification() {}

func (*InstallRequest_SslProfileId) isInstallRequest_SignatureVerification() {}

type TransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*TransferRequest_SoftwareBundleName
	//	*TransferRequest_Contents
	//	*TransferRequest_Hash
	Request       isTransferRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{9}
}

func (x *TransferRequest) GetRequest() isTransferRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TransferRequest) GetSoftwareBundleName() string {
	if x != nil {
		if x, ok := x.Request.(*TransferRequest_SoftwareBundleName); ok {
			return x.SoftwareBundleName
		}
	}
	return ""
}

func (x *TransferRequest) GetContents() []byte {
	if x != nil {
		if x, ok := x.Request.(*TransferRequest_Contents); ok {
			return x.Contents
		}
	}
	return nil
}

func (x *TransferRequest) GetHash() *types.HashType {
	if x != nil {
		if x, ok := x.Request.(*TransferRequest_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

type isTransferRequest_Request interface {
	isTransferRequest_Request()
}

type TransferRequest_SoftwareBundleName struct {
	SoftwareBundleName string `protobuf:"bytes,1,opt,name=software_bundle_name,json=softwareBundleName,proto3,oneof"`
}

type TransferRequest_Contents struct {
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3,oneof"`
}

type TransferRequest_Hash struct {
	Hash *types.HashType `protobuf:"bytes,3,opt,name=hash,proto3,oneof"`
}

func (*TransferRequest_SoftwareBundleName) isTransferRequest_Request() {}

func (*TransferRequest_Contents) isTransferRequest_Request() {}

func (*TransferRequest_Hash) isTransferRequest_Request() {}

type ListSoftwareBundlesResponse_Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Release       string                 `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSoftwareBundlesResponse_Package) Reset() {
	*x = ListSoftwareBundlesResponse_Package{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSoftwareBundlesResponse_Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareBundlesResponse_Package) ProtoMessage() {}

func (x *ListSoftwareBundlesResponse_Package) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareBundlesResponse_Package.ProtoReflect.Descriptor instead.
func (*ListSoftwareBundlesResponse_Package) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListSoftwareBundlesResponse_Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_Package) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

type ListSoftwareBundlesResponse_SoftwareBundle struct {
	state             protoimpl.MessageState                    `protogen:"open.v1"`
	Name              string                                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                                    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Release           string                                    `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Description       string                                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	InstallStatus     ListSoftwareBundlesResponse_InstallStatus `protobuf:"varint,6,opt,name=install_status,json=installStatus,proto3,enum=gnoi.software_bundle.ListSoftwareBundlesResponse_InstallStatus" json:"install_status,omitempty"`
	InstallAtBoot     bool                                      `protobuf:"varint,7,opt,name=install_at_boot,json=installAtBoot,proto3" json:"install_at_boot,omitempty"`
	SignatureValid    bool                                      `protobuf:"varint,8,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	Available         bool                                      `protobuf:"varint,9,opt,name=available,proto3" json:"available,omitempty"`
	Errors            string                                    `protobuf:"bytes,10,opt,name=errors,proto3" json:"errors,omitempty"`
	Packages          []*ListSoftwareBundlesResponse_Package    `protobuf:"bytes,11,rep,name=packages,proto3" json:"packages,omitempty"`
	AffectedServices  []string                                  `protobuf:"bytes,12,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	ServicesToRestart []string                                  `protobuf:"bytes,13,rep,name=services_to_restart,json=servicesToRestart,proto3" json:"services_to_restart,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) Reset() {
	*x = ListSoftwareBundlesResponse_SoftwareBundle{}
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSoftwareBundlesResponse_SoftwareBundle) ProtoMessage() {}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSoftwareBundlesResponse_SoftwareBundle.ProtoReflect.Descriptor instead.
func (*ListSoftwareBundlesResponse_SoftwareBundle) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetInstallStatus() ListSoftwareBundlesResponse_InstallStatus {
	if x != nil {
		return x.InstallStatus
	}
	return ListSoftwareBundlesResponse_UNSPECIFIED
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetInstallAtBoot() bool {
	if x != nil {
		return x.InstallAtBoot
	}
	return false
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetPackages() []*ListSoftwareBundlesResponse_Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *ListSoftwareBundlesResponse_SoftwareBundle) GetServicesToRestart() []string {
	if x != nil {
		return x.ServicesToRestart
	}
	return nil
}

var File_github_com_openconfig_gnoi_software_bundle_software_bundle_proto protoreflect.FileDescriptor

const file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDesc = "" +
	"\n" +
	"@github.com/openconfig/gnoi/software_bundle/software_bundle.proto\x12\x14gnoi.software_bundle\x1a,github.com/openconfig/gnoi/types/types.proto\"\x1c\n" +
	"\x1aListSoftwareBundlesRequest\"\xd6\x06\n" +
	"\x1bListSoftwareBundlesResponse\x12k\n" +
	"\x10software_bundles\x18\x01 \x03(\v2@.gnoi.software_bundle.ListSoftwareBundlesResponse.SoftwareBundleR\x0fsoftwareBundles\x1aQ\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\arelease\x18\x03 \x01(\tR\arelease\x1a\x9d\x04\n" +
	"\x0eSoftwareBundle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\arelease\x18\x03 \x01(\tR\arelease\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12f\n" +
	"\x0einstall_status\x18\x06 \x01(\x0e2?.gnoi.software_bundle.ListSoftwareBundlesResponse.InstallStatusR\rinstallStatus\x12&\n" +
	"\x0finstall_at_boot\x18\a \x01(\bR\rinstallAtBoot\x12'\n" +
	"\x0fsignature_valid\x18\b \x01(\bR\x0esignatureValid\x12\x1c\n" +
	"\tavailable\x18\t \x01(\bR\tavailable\x12\x16\n" +
	"\x06errors\x18\n" +
	" \x01(\tR\x06errors\x12U\n" +
	"\bpackages\x18\v \x03(\v29.gnoi.software_bundle.ListSoftwareBundlesResponse.PackageR\bpackages\x12+\n" +
	"\x11affected_services\x18\f \x03(\tR\x10affectedServices\x12.\n" +
	"\x13services_to_restart\x18\r \x03(\tR\x11servicesToRestart\"W\n" +
	"\rInstallStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tINSTALLED\x10\x01\x12\x11\n" +
	"\rNOT_INSTALLED\x10\x02\x12\x13\n" +
	"\x0fFORCE_INSTALLED\x10\x03\" \n" +
	"\x1eFinalizeSoftwareBundlesRequest\"!\n" +
	"\x1fFinalizeSoftwareBundlesResponse\"J\n" +
	"\x1eUninstallSoftwareBundleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"!\n" +
	"\x1fUninstallSoftwareBundleResponse\"\xd3\x01\n" +
	"\x1dInstallSoftwareBundleResponse\x12g\n" +
	"\x0facknowledgement\x18\x03 \x01(\x0e2=.gnoi.software_bundle.InstallSoftwareBundleResponse.OperationR\x0facknowledgement\"I\n" +
	"\tOperation\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TRANSFER_COMPLETE\x10\x01\x12\x14\n" +
	"\x10INSTALL_COMPLETE\x10\x02\"\xce\x01\n" +
	"\x1cInstallSoftwareBundleRequest\x12R\n" +
	"\x10transfer_request\x18\x01 \x01(\v2%.gnoi.software_bundle.TransferRequestH\x00R\x0ftransferRequest\x12O\n" +
	"\x0finstall_request\x18\x02 \x01(\v2$.gnoi.software_bundle.InstallRequestH\x00R\x0einstallRequestB\t\n" +
	"\arequest\"\xcc\x02\n" +
	"\x0eInstallRequest\x120\n" +
	"\x14software_bundle_name\x18\x01 \x01(\tR\x12softwareBundleName\x12&\n" +
	"\x0fload_after_boot\x18\x03 \x01(\bR\rloadAfterBoot\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\x12J\n" +
	"\x06source\x18\x05 \x01(\x0e20.gnoi.software_bundle.InstallRequest.TrustSourceH\x00R\x06source\x12&\n" +
	"\x0essl_profile_id\x18\x06 \x01(\tH\x00R\fsslProfileId\"<\n" +
	"\vTrustSource\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06IGNORE\x10\x01\x12\x10\n" +
	"\fMANUFACTURER\x10\x02B\x18\n" +
	"\x16signature_verification\"\x9a\x01\n" +
	"\x0fTransferRequest\x122\n" +
	"\x14software_bundle_name\x18\x01 \x01(\tH\x00R\x12softwareBundleName\x12\x1c\n" +
	"\bcontents\x18\x02 \x01(\fH\x00R\bcontents\x12*\n" +
	"\x04hash\x18\x03 \x01(\v2\x14.gnoi.types.HashTypeH\x00R\x04hashB\t\n" +
	"\arequest2\xa5\x04\n" +
	"\x0eSoftwareBundle\x12z\n" +
	"\x13ListSoftwareBundles\x120.gnoi.software_bundle.ListSoftwareBundlesRequest\x1a1.gnoi.software_bundle.ListSoftwareBundlesResponse\x12\x86\x01\n" +
	"\x17FinalizeSoftwareBundles\x124.gnoi.software_bundle.FinalizeSoftwareBundlesRequest\x1a5.gnoi.software_bundle.FinalizeSoftwareBundlesResponse\x12\x84\x01\n" +
	"\x15InstallSoftwareBundle\x122.gnoi.software_bundle.InstallSoftwareBundleRequest\x1a3.gnoi.software_bundle.InstallSoftwareBundleResponse(\x010\x01\x12\x86\x01\n" +
	"\x17UninstallSoftwareBundle\x124.gnoi.software_bundle.UninstallSoftwareBundleRequest\x1a5.gnoi.software_bundle.UninstallSoftwareBundleResponseB4\xd2>\x050.1.0Z*github.com/openconfig/gnoi/software_bundleb\x06proto3"

var (
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescOnce sync.Once
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescData []byte
)

func file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDesc), len(file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDesc)))
	})
	return file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDescData
}

var file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_goTypes = []any{
	(ListSoftwareBundlesResponse_InstallStatus)(0),     // 0: gnoi.software_bundle.ListSoftwareBundlesResponse.InstallStatus
	(InstallSoftwareBundleResponse_Operation)(0),       // 1: gnoi.software_bundle.InstallSoftwareBundleResponse.Operation
	(InstallRequest_TrustSource)(0),                    // 2: gnoi.software_bundle.InstallRequest.TrustSource
	(*ListSoftwareBundlesRequest)(nil),                 // 3: gnoi.software_bundle.ListSoftwareBundlesRequest
	(*ListSoftwareBundlesResponse)(nil),                // 4: gnoi.software_bundle.ListSoftwareBundlesResponse
	(*FinalizeSoftwareBundlesRequest)(nil),             // 5: gnoi.software_bundle.FinalizeSoftwareBundlesRequest
	(*FinalizeSoftwareBundlesResponse)(nil),            // 6: gnoi.software_bundle.FinalizeSoftwareBundlesResponse
	(*UninstallSoftwareBundleRequest)(nil),             // 7: gnoi.software_bundle.UninstallSoftwareBundleRequest
	(*UninstallSoftwareBundleResponse)(nil),            // 8: gnoi.software_bundle.UninstallSoftwareBundleResponse
	(*InstallSoftwareBundleResponse)(nil),              // 9: gnoi.software_bundle.InstallSoftwareBundleResponse
	(*InstallSoftwareBundleRequest)(nil),               // 10: gnoi.software_bundle.InstallSoftwareBundleRequest
	(*InstallRequest)(nil),                             // 11: gnoi.software_bundle.InstallRequest
	(*TransferRequest)(nil),                            // 12: gnoi.software_bundle.TransferRequest
	(*ListSoftwareBundlesResponse_Package)(nil),        // 13: gnoi.software_bundle.ListSoftwareBundlesResponse.Package
	(*ListSoftwareBundlesResponse_SoftwareBundle)(nil), // 14: gnoi.software_bundle.ListSoftwareBundlesResponse.SoftwareBundle
	(*types.HashType)(nil),                             // 15: gnoi.types.HashType
}
var file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_depIdxs = []int32{
	14, // 0: gnoi.software_bundle.ListSoftwareBundlesResponse.software_bundles:type_name -> gnoi.software_bundle.ListSoftwareBundlesResponse.SoftwareBundle
	1,  // 1: gnoi.software_bundle.InstallSoftwareBundleResponse.acknowledgement:type_name -> gnoi.software_bundle.InstallSoftwareBundleResponse.Operation
	12, // 2: gnoi.software_bundle.InstallSoftwareBundleRequest.transfer_request:type_name -> gnoi.software_bundle.TransferRequest
	11, // 3: gnoi.software_bundle.InstallSoftwareBundleRequest.install_request:type_name -> gnoi.software_bundle.InstallRequest
	2,  // 4: gnoi.software_bundle.InstallRequest.source:type_name -> gnoi.software_bundle.InstallRequest.TrustSource
	15, // 5: gnoi.software_bundle.TransferRequest.hash:type_name -> gnoi.types.HashType
	0,  // 6: gnoi.software_bundle.ListSoftwareBundlesResponse.SoftwareBundle.install_status:type_name -> gnoi.software_bundle.ListSoftwareBundlesResponse.InstallStatus
	13, // 7: gnoi.software_bundle.ListSoftwareBundlesResponse.SoftwareBundle.packages:type_name -> gnoi.software_bundle.ListSoftwareBundlesResponse.Package
	3,  // 8: gnoi.software_bundle.SoftwareBundle.ListSoftwareBundles:input_type -> gnoi.software_bundle.ListSoftwareBundlesRequest
	5,  // 9: gnoi.software_bundle.SoftwareBundle.FinalizeSoftwareBundles:input_type -> gnoi.software_bundle.FinalizeSoftwareBundlesRequest
	10, // 10: gnoi.software_bundle.SoftwareBundle.InstallSoftwareBundle:input_type -> gnoi.software_bundle.InstallSoftwareBundleRequest
	7,  // 11: gnoi.software_bundle.SoftwareBundle.UninstallSoftwareBundle:input_type -> gnoi.software_bundle.UninstallSoftwareBundleRequest
	4,  // 12: gnoi.software_bundle.SoftwareBundle.ListSoftwareBundles:output_type -> gnoi.software_bundle.ListSoftwareBundlesResponse
	6,  // 13: gnoi.software_bundle.SoftwareBundle.FinalizeSoftwareBundles:output_type -> gnoi.software_bundle.FinalizeSoftwareBundlesResponse
	9,  // 14: gnoi.software_bundle.SoftwareBundle.InstallSoftwareBundle:output_type -> gnoi.software_bundle.InstallSoftwareBundleResponse
	8,  // 15: gnoi.software_bundle.SoftwareBundle.UninstallSoftwareBundle:output_type -> gnoi.software_bundle.UninstallSoftwareBundleResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_init() }
func file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_init() {
	if File_github_com_openconfig_gnoi_software_bundle_software_bundle_proto != nil {
		return
	}
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[7].OneofWrappers = []any{
		(*InstallSoftwareBundleRequest_TransferRequest)(nil),
		(*InstallSoftwareBundleRequest_InstallRequest)(nil),
	}
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[8].OneofWrappers = []any{
		(*InstallRequest_Source)(nil),
		(*InstallRequest_SslProfileId)(nil),
	}
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes[9].OneofWrappers = []any{
		(*TransferRequest_SoftwareBundleName)(nil),
		(*TransferRequest_Contents)(nil),
		(*TransferRequest_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDesc), len(file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_depIdxs,
		EnumInfos:         file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_enumTypes,
		MessageInfos:      file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_gnoi_software_bundle_software_bundle_proto = out.File
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_goTypes = nil
	file_github_com_openconfig_gnoi_software_bundle_software_bundle_proto_depIdxs = nil
}
