// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/gnoi/types.proto

/*
Package gnoi is a generated protocol buffer package.

It is generated from these files:
	github.com/openconfig/gnoi/types.proto

It has these top-level messages:
	HashType
	Path
*/
package gnoi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Generic Layer 3 Protocol enumeration.
type L3Protocol int32

const (
	L3Protocol_UNSPECIFIED L3Protocol = 0
	L3Protocol_IPV4        L3Protocol = 1
	L3Protocol_IPV6        L3Protocol = 2
)

var L3Protocol_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "IPV4",
	2: "IPV6",
}
var L3Protocol_value = map[string]int32{
	"UNSPECIFIED": 0,
	"IPV4":        1,
	"IPV6":        2,
}

func (x L3Protocol) String() string {
	return proto.EnumName(L3Protocol_name, int32(x))
}
func (L3Protocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HashType_HashMethod int32

const (
	HashType_UNSPECIFIED HashType_HashMethod = 0
	HashType_SHA256      HashType_HashMethod = 1
	HashType_SHA512      HashType_HashMethod = 2
)

var HashType_HashMethod_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "SHA256",
	2: "SHA512",
}
var HashType_HashMethod_value = map[string]int32{
	"UNSPECIFIED": 0,
	"SHA256":      1,
	"SHA512":      2,
}

func (x HashType_HashMethod) String() string {
	return proto.EnumName(HashType_HashMethod_name, int32(x))
}
func (HashType_HashMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// HashType defines the valid hash methods for data verification.  UNSPECIFIED
// should be treated an error.
type HashType struct {
	Method HashType_HashMethod `protobuf:"varint,1,opt,name=method,enum=gnoi.HashType_HashMethod" json:"method,omitempty"`
	Hash   []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *HashType) Reset()                    { *m = HashType{} }
func (m *HashType) String() string            { return proto.CompactTextString(m) }
func (*HashType) ProtoMessage()               {}
func (*HashType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HashType) GetMethod() HashType_HashMethod {
	if m != nil {
		return m.Method
	}
	return HashType_UNSPECIFIED
}

func (m *HashType) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// OpenConfig path representation of the target.
// eg. /interfaces/interface[name=et-1/0/0]
type Path struct {
	Elements []string `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Path) GetElements() []string {
	if m != nil {
		return m.Elements
	}
	return nil
}

func init() {
	proto.RegisterType((*HashType)(nil), "gnoi.HashType")
	proto.RegisterType((*Path)(nil), "gnoi.Path")
	proto.RegisterEnum("gnoi.L3Protocol", L3Protocol_name, L3Protocol_value)
	proto.RegisterEnum("gnoi.HashType_HashMethod", HashType_HashMethod_name, HashType_HashMethod_value)
}

func init() { proto.RegisterFile("github.com/openconfig/gnoi/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0xd7, 0x4f, 0xcf, 0xcb, 0xcf, 0xd4, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x28, 0x75, 0x30, 0x72, 0x71, 0x78, 0x24, 0x16, 0x67, 0x84,
	0x54, 0x16, 0xa4, 0x0a, 0x19, 0x72, 0xb1, 0xe5, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0xf0, 0x19, 0x49, 0xea, 0x81, 0xd4, 0xe8, 0xc1, 0xe4, 0xc1, 0x0c, 0x5f, 0xb0, 0x82,
	0x20, 0xa8, 0x42, 0x21, 0x21, 0x2e, 0x96, 0x8c, 0xc4, 0xe2, 0x0c, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0x9e, 0x20, 0x30, 0x5b, 0xc9, 0x94, 0x8b, 0x0b, 0xa1, 0x52, 0x88, 0x9f, 0x8b, 0x3b, 0xd4, 0x2f,
	0x38, 0xc0, 0xd5, 0xd9, 0xd3, 0xcd, 0xd3, 0xd5, 0x45, 0x80, 0x41, 0x88, 0x8b, 0x8b, 0x2d, 0xd8,
	0xc3, 0xd1, 0xc8, 0xd4, 0x4c, 0x80, 0x11, 0xca, 0x36, 0x35, 0x34, 0x12, 0x60, 0x52, 0x52, 0xe2,
	0x62, 0x09, 0x48, 0x2c, 0xc9, 0x10, 0x92, 0xe2, 0xe2, 0x48, 0xcd, 0x49, 0xcd, 0x4d, 0xcd, 0x2b,
	0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf3, 0xb5, 0x0c, 0xb9, 0xb8, 0x7c, 0x8c,
	0x03, 0x40, 0xee, 0x4f, 0xce, 0xcf, 0xc1, 0x34, 0x9a, 0x83, 0x8b, 0xc5, 0x33, 0x20, 0xcc, 0x44,
	0x80, 0x11, 0xca, 0x32, 0x13, 0x60, 0x4a, 0x62, 0x03, 0x7b, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xb0, 0x4d, 0xd2, 0x1e, 0x18, 0x01, 0x00, 0x00,
}
