// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: github.com/openconfig/gnoi/pon/pon.proto

package pon

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	types "github.com/openconfig/gnoi/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing the firmware type for download operations.
type FWType int32

const (
	FWType_FW_TYPE_UNSPECIFIED  FWType = 0 // Unspecified firmware type (invalid)
	FWType_FW_TYPE_OLT_FIRMWARE FWType = 1 // OLT firmware
	FWType_FW_TYPE_ONU_FIRMWARE FWType = 2 // ONU firmware
)

// Enum value maps for FWType.
var (
	FWType_name = map[int32]string{
		0: "FW_TYPE_UNSPECIFIED",
		1: "FW_TYPE_OLT_FIRMWARE",
		2: "FW_TYPE_ONU_FIRMWARE",
	}
	FWType_value = map[string]int32{
		"FW_TYPE_UNSPECIFIED":  0,
		"FW_TYPE_OLT_FIRMWARE": 1,
		"FW_TYPE_ONU_FIRMWARE": 2,
	}
)

func (x FWType) Enum() *FWType {
	p := new(FWType)
	*p = x
	return p
}

func (x FWType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FWType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[0].Descriptor()
}

func (FWType) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[0]
}

func (x FWType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FWType.Descriptor instead.
func (FWType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{0}
}

// Enum representing the device state type for clear operations.
type DeviceStateType int32

const (
	DeviceStateType_DEVICE_STATE_UNSPECIFIED DeviceStateType = 0
	DeviceStateType_DEVICE_STATE_LOGS        DeviceStateType = 1 // Clear logs
	DeviceStateType_DEVICE_STATE_STATISTICS  DeviceStateType = 2 // Clear statistics
)

// Enum value maps for DeviceStateType.
var (
	DeviceStateType_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "DEVICE_STATE_LOGS",
		2: "DEVICE_STATE_STATISTICS",
	}
	DeviceStateType_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"DEVICE_STATE_LOGS":        1,
		"DEVICE_STATE_STATISTICS":  2,
	}
)

func (x DeviceStateType) Enum() *DeviceStateType {
	p := new(DeviceStateType)
	*p = x
	return p
}

func (x DeviceStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[1].Descriptor()
}

func (DeviceStateType) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[1]
}

func (x DeviceStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStateType.Descriptor instead.
func (DeviceStateType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{1}
}

// Enum representing the controller administrative status.
type ControllerAdminStatus int32

const (
	ControllerAdminStatus_ADMIN_STATUS_UNSPECIFIED ControllerAdminStatus = 0
	ControllerAdminStatus_ADMIN_STATUS_PAUSE       ControllerAdminStatus = 1 // Pause the PON Controller
	ControllerAdminStatus_ADMIN_STATUS_START       ControllerAdminStatus = 2 // Start the PON Controller
)

// Enum value maps for ControllerAdminStatus.
var (
	ControllerAdminStatus_name = map[int32]string{
		0: "ADMIN_STATUS_UNSPECIFIED",
		1: "ADMIN_STATUS_PAUSE",
		2: "ADMIN_STATUS_START",
	}
	ControllerAdminStatus_value = map[string]int32{
		"ADMIN_STATUS_UNSPECIFIED": 0,
		"ADMIN_STATUS_PAUSE":       1,
		"ADMIN_STATUS_START":       2,
	}
)

func (x ControllerAdminStatus) Enum() *ControllerAdminStatus {
	p := new(ControllerAdminStatus)
	*p = x
	return p
}

func (x ControllerAdminStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerAdminStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[2].Descriptor()
}

func (ControllerAdminStatus) Type() protoreflect.EnumType {
	return &file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes[2]
}

func (x ControllerAdminStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerAdminStatus.Descriptor instead.
func (ControllerAdminStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{2}
}

// Common message for streaming file contents to be written on the target
// device.
type PonFilePutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PonFilePutRequest_Filename
	//	*PonFilePutRequest_Contents
	//	*PonFilePutRequest_Hash
	Request       isPonFilePutRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PonFilePutRequest) Reset() {
	*x = PonFilePutRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PonFilePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PonFilePutRequest) ProtoMessage() {}

func (x *PonFilePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PonFilePutRequest.ProtoReflect.Descriptor instead.
func (*PonFilePutRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{0}
}

func (x *PonFilePutRequest) GetRequest() isPonFilePutRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PonFilePutRequest) GetFilename() string {
	if x != nil {
		if x, ok := x.Request.(*PonFilePutRequest_Filename); ok {
			return x.Filename
		}
	}
	return ""
}

func (x *PonFilePutRequest) GetContents() []byte {
	if x != nil {
		if x, ok := x.Request.(*PonFilePutRequest_Contents); ok {
			return x.Contents
		}
	}
	return nil
}

func (x *PonFilePutRequest) GetHash() *types.HashType {
	if x != nil {
		if x, ok := x.Request.(*PonFilePutRequest_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

type isPonFilePutRequest_Request interface {
	isPonFilePutRequest_Request()
}

type PonFilePutRequest_Filename struct {
	// Name of the file to be written on the target device.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type PonFilePutRequest_Contents struct {
	// Contents of the file to be written, streamed in multiple messages.
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3,oneof"`
}

type PonFilePutRequest_Hash struct {
	// Hash of the file contents for verification. Also marks end of stream.
	Hash *types.HashType `protobuf:"bytes,3,opt,name=hash,proto3,oneof"`
}

func (*PonFilePutRequest_Filename) isPonFilePutRequest_Request() {}

func (*PonFilePutRequest_Contents) isPonFilePutRequest_Request() {}

func (*PonFilePutRequest_Hash) isPonFilePutRequest_Request() {}

// Request message for FirmwareDownload RPC.
type FirmwareDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of firmware to download (OLT or ONU)
	FwType FWType `protobuf:"varint,1,opt,name=fw_type,json=fwType,proto3,enum=gnoi.pon.FWType" json:"fw_type,omitempty"`
	// Manufacturer name of the target device
	Manufacturer string `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Firmware version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// List of target device models the firmware is compatible with
	ModelList []string `protobuf:"bytes,4,rep,name=model_list,json=modelList,proto3" json:"model_list,omitempty"`
	// Streaming file contents to be written on the target device
	FilePutRequest *PonFilePutRequest `protobuf:"bytes,5,opt,name=file_put_request,json=filePutRequest,proto3" json:"file_put_request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FirmwareDownloadRequest) Reset() {
	*x = FirmwareDownloadRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareDownloadRequest) ProtoMessage() {}

func (x *FirmwareDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareDownloadRequest.ProtoReflect.Descriptor instead.
func (*FirmwareDownloadRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{1}
}

func (x *FirmwareDownloadRequest) GetFwType() FWType {
	if x != nil {
		return x.FwType
	}
	return FWType_FW_TYPE_UNSPECIFIED
}

func (x *FirmwareDownloadRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *FirmwareDownloadRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareDownloadRequest) GetModelList() []string {
	if x != nil {
		return x.ModelList
	}
	return nil
}

func (x *FirmwareDownloadRequest) GetFilePutRequest() *PonFilePutRequest {
	if x != nil {
		return x.FilePutRequest
	}
	return nil
}

// Request message for OnuServiceConfigDownload RPC.
type OnuServiceConfigDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service config file must always be a JSON file, otherwise the request
	// will be rejected.
	// Streaming file contents to be written on the target device
	FilePutRequest *PonFilePutRequest `protobuf:"bytes,1,opt,name=file_put_request,json=filePutRequest,proto3" json:"file_put_request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OnuServiceConfigDownloadRequest) Reset() {
	*x = OnuServiceConfigDownloadRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnuServiceConfigDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuServiceConfigDownloadRequest) ProtoMessage() {}

func (x *OnuServiceConfigDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuServiceConfigDownloadRequest.ProtoReflect.Descriptor instead.
func (*OnuServiceConfigDownloadRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{2}
}

func (x *OnuServiceConfigDownloadRequest) GetFilePutRequest() *PonFilePutRequest {
	if x != nil {
		return x.FilePutRequest
	}
	return nil
}

// Request message for ControllerClear RPC.
type ControllerClearRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifier for the target PON Controller
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of state data to clear (logs, statistics)
	DeviceState   DeviceStateType `protobuf:"varint,2,opt,name=device_state,json=deviceState,proto3,enum=gnoi.pon.DeviceStateType" json:"device_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerClearRequest) Reset() {
	*x = ControllerClearRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerClearRequest) ProtoMessage() {}

func (x *ControllerClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerClearRequest.ProtoReflect.Descriptor instead.
func (*ControllerClearRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ControllerClearRequest) GetDeviceState() DeviceStateType {
	if x != nil {
		return x.DeviceState
	}
	return DeviceStateType_DEVICE_STATE_UNSPECIFIED
}

// Request message for ControllerSetStatus RPC.
type ControllerSetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifier for the target PON Controller
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// PON Controller administrative status
	AdminStatus   ControllerAdminStatus `protobuf:"varint,2,opt,name=admin_status,json=adminStatus,proto3,enum=gnoi.pon.ControllerAdminStatus" json:"admin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerSetStatusRequest) Reset() {
	*x = ControllerSetStatusRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerSetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerSetStatusRequest) ProtoMessage() {}

func (x *ControllerSetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerSetStatusRequest.ProtoReflect.Descriptor instead.
func (*ControllerSetStatusRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{4}
}

func (x *ControllerSetStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ControllerSetStatusRequest) GetAdminStatus() ControllerAdminStatus {
	if x != nil {
		return x.AdminStatus
	}
	return ControllerAdminStatus_ADMIN_STATUS_UNSPECIFIED
}

// Request message for OltAllowOnuRegistration RPC.
type OltAllowOnuRegistrationRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OltName string                 `protobuf:"bytes,1,opt,name=olt_name,json=oltName,proto3" json:"olt_name,omitempty"` // Name identifier for the target OLT device
	// ONU identifier: 'ALL' | ONU Serial Number (XGS-PON) |
	// ONU MAC Address (EPON)
	OnuId         string `protobuf:"bytes,2,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltAllowOnuRegistrationRequest) Reset() {
	*x = OltAllowOnuRegistrationRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltAllowOnuRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltAllowOnuRegistrationRequest) ProtoMessage() {}

func (x *OltAllowOnuRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltAllowOnuRegistrationRequest.ProtoReflect.Descriptor instead.
func (*OltAllowOnuRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{5}
}

func (x *OltAllowOnuRegistrationRequest) GetOltName() string {
	if x != nil {
		return x.OltName
	}
	return ""
}

func (x *OltAllowOnuRegistrationRequest) GetOnuId() string {
	if x != nil {
		return x.OnuId
	}
	return ""
}

// Request message for OltClear RPC.
type OltClearRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifier for the target OLT device
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of state data to clear (logs, statistics)
	DeviceState   DeviceStateType `protobuf:"varint,2,opt,name=device_state,json=deviceState,proto3,enum=gnoi.pon.DeviceStateType" json:"device_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltClearRequest) Reset() {
	*x = OltClearRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltClearRequest) ProtoMessage() {}

func (x *OltClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltClearRequest.ProtoReflect.Descriptor instead.
func (*OltClearRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{6}
}

func (x *OltClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OltClearRequest) GetDeviceState() DeviceStateType {
	if x != nil {
		return x.DeviceState
	}
	return DeviceStateType_DEVICE_STATE_UNSPECIFIED
}

// Request message for OltDisableOnu RPC.
type OltDisableOnuRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OltName string                 `protobuf:"bytes,1,opt,name=olt_name,json=oltName,proto3" json:"olt_name,omitempty"` // Name identifier for the target OLT device
	// ONU identifier: Serial Number (XGS-PON) | MAC Address (EPON)
	OnuId         string `protobuf:"bytes,2,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"`
	Disable       bool   `protobuf:"varint,3,opt,name=disable,proto3" json:"disable,omitempty"` // true=disable, false=enable the ONU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltDisableOnuRequest) Reset() {
	*x = OltDisableOnuRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltDisableOnuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltDisableOnuRequest) ProtoMessage() {}

func (x *OltDisableOnuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltDisableOnuRequest.ProtoReflect.Descriptor instead.
func (*OltDisableOnuRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{7}
}

func (x *OltDisableOnuRequest) GetOltName() string {
	if x != nil {
		return x.OltName
	}
	return ""
}

func (x *OltDisableOnuRequest) GetOnuId() string {
	if x != nil {
		return x.OnuId
	}
	return ""
}

func (x *OltDisableOnuRequest) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

// Request message for OltReset RPC.
type OltResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name identifier for the target OLT device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltResetRequest) Reset() {
	*x = OltResetRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltResetRequest) ProtoMessage() {}

func (x *OltResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltResetRequest.ProtoReflect.Descriptor instead.
func (*OltResetRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{8}
}

func (x *OltResetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for OnuClearAbortedUpgrade RPC.
type OnuClearAbortedUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name identifier for the target ONU device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnuClearAbortedUpgradeRequest) Reset() {
	*x = OnuClearAbortedUpgradeRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnuClearAbortedUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuClearAbortedUpgradeRequest) ProtoMessage() {}

func (x *OnuClearAbortedUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuClearAbortedUpgradeRequest.ProtoReflect.Descriptor instead.
func (*OnuClearAbortedUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{9}
}

func (x *OnuClearAbortedUpgradeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for OnuClear RPC.
type OnuClearRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifier for the target ONU device
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of state data to clear (logs, statistics)
	DeviceState   DeviceStateType `protobuf:"varint,2,opt,name=device_state,json=deviceState,proto3,enum=gnoi.pon.DeviceStateType" json:"device_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnuClearRequest) Reset() {
	*x = OnuClearRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnuClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuClearRequest) ProtoMessage() {}

func (x *OnuClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuClearRequest.ProtoReflect.Descriptor instead.
func (*OnuClearRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{10}
}

func (x *OnuClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnuClearRequest) GetDeviceState() DeviceStateType {
	if x != nil {
		return x.DeviceState
	}
	return DeviceStateType_DEVICE_STATE_UNSPECIFIED
}

// Request message for OnuReset RPC.
type OnuResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name identifier for the target ONU device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnuResetRequest) Reset() {
	*x = OnuResetRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnuResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuResetRequest) ProtoMessage() {}

func (x *OnuResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuResetRequest.ProtoReflect.Descriptor instead.
func (*OnuResetRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{11}
}

func (x *OnuResetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for OltProtectionArm RPC.
type OltProtectionArmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name identifier for the target OLT device
	// true=arm (default), false=disarm protection switching
	Arm bool `protobuf:"varint,2,opt,name=arm,proto3" json:"arm,omitempty"`
	// true=force protection switch, false=normal (default)
	ForceSwitch   bool `protobuf:"varint,3,opt,name=force_switch,json=forceSwitch,proto3" json:"force_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltProtectionArmRequest) Reset() {
	*x = OltProtectionArmRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltProtectionArmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltProtectionArmRequest) ProtoMessage() {}

func (x *OltProtectionArmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltProtectionArmRequest.ProtoReflect.Descriptor instead.
func (*OltProtectionArmRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{12}
}

func (x *OltProtectionArmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OltProtectionArmRequest) GetArm() bool {
	if x != nil {
		return x.Arm
	}
	return false
}

func (x *OltProtectionArmRequest) GetForceSwitch() bool {
	if x != nil {
		return x.ForceSwitch
	}
	return false
}

// Request message for OltProtectionSwitch RPC.
type OltProtectionSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name identifier for the target OLT device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltProtectionSwitchRequest) Reset() {
	*x = OltProtectionSwitchRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltProtectionSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltProtectionSwitchRequest) ProtoMessage() {}

func (x *OltProtectionSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltProtectionSwitchRequest.ProtoReflect.Descriptor instead.
func (*OltProtectionSwitchRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{13}
}

func (x *OltProtectionSwitchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for DbManagerDbRestart RPC.
type DbManagerDbRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbManagerDbRestartRequest) Reset() {
	*x = DbManagerDbRestartRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbManagerDbRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbManagerDbRestartRequest) ProtoMessage() {}

func (x *DbManagerDbRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbManagerDbRestartRequest.ProtoReflect.Descriptor instead.
func (*DbManagerDbRestartRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{14}
}

// Request message for DbManagerServerStatisticsClear RPC.
type DbManagerServerStatisticsClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbManagerServerStatisticsClearRequest) Reset() {
	*x = DbManagerServerStatisticsClearRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbManagerServerStatisticsClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbManagerServerStatisticsClearRequest) ProtoMessage() {}

func (x *DbManagerServerStatisticsClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbManagerServerStatisticsClearRequest.ProtoReflect.Descriptor instead.
func (*DbManagerServerStatisticsClearRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{15}
}

// Request message for DbManagerDbClientStatisticsClear RPC.
type DbManagerDbClientStatisticsClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbManagerDbClientStatisticsClearRequest) Reset() {
	*x = DbManagerDbClientStatisticsClearRequest{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbManagerDbClientStatisticsClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbManagerDbClientStatisticsClearRequest) ProtoMessage() {}

func (x *DbManagerDbClientStatisticsClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbManagerDbClientStatisticsClearRequest.ProtoReflect.Descriptor instead.
func (*DbManagerDbClientStatisticsClearRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{16}
}

// Common response message for PON RPCs.
type PonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Indicates whether the operation was successful
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the operation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PonResponse) Reset() {
	*x = PonResponse{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PonResponse) ProtoMessage() {}

func (x *PonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PonResponse.ProtoReflect.Descriptor instead.
func (*PonResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{17}
}

func (x *PonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response message for PON Database Manager RPCs.
// Returns status string and optional error message from the db-manager
// backend.
type DbManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Indicates whether the operation was successful
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // Status string returned by the db-manager backend
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the operation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbManagerResponse) Reset() {
	*x = DbManagerResponse{}
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbManagerResponse) ProtoMessage() {}

func (x *DbManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbManagerResponse.ProtoReflect.Descriptor instead.
func (*DbManagerResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP(), []int{18}
}

func (x *DbManagerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DbManagerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DbManagerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_github_com_openconfig_gnoi_pon_pon_proto protoreflect.FileDescriptor

const file_github_com_openconfig_gnoi_pon_pon_proto_rawDesc = "" +
	"\n" +
	"(github.com/openconfig/gnoi/pon/pon.proto\x12\bgnoi.pon\x1a,github.com/openconfig/gnoi/types/types.proto\"\x86\x01\n" +
	"\x11PonFilePutRequest\x12\x1c\n" +
	"\bfilename\x18\x01 \x01(\tH\x00R\bfilename\x12\x1c\n" +
	"\bcontents\x18\x02 \x01(\fH\x00R\bcontents\x12*\n" +
	"\x04hash\x18\x03 \x01(\v2\x14.gnoi.types.HashTypeH\x00R\x04hashB\t\n" +
	"\arequest\"\xe8\x01\n" +
	"\x17FirmwareDownloadRequest\x12)\n" +
	"\afw_type\x18\x01 \x01(\x0e2\x10.gnoi.pon.FWTypeR\x06fwType\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"model_list\x18\x04 \x03(\tR\tmodelList\x12E\n" +
	"\x10file_put_request\x18\x05 \x01(\v2\x1b.gnoi.pon.PonFilePutRequestR\x0efilePutRequest\"h\n" +
	"\x1fOnuServiceConfigDownloadRequest\x12E\n" +
	"\x10file_put_request\x18\x01 \x01(\v2\x1b.gnoi.pon.PonFilePutRequestR\x0efilePutRequest\"j\n" +
	"\x16ControllerClearRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\fdevice_state\x18\x02 \x01(\x0e2\x19.gnoi.pon.DeviceStateTypeR\vdeviceState\"t\n" +
	"\x1aControllerSetStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\fadmin_status\x18\x02 \x01(\x0e2\x1f.gnoi.pon.ControllerAdminStatusR\vadminStatus\"R\n" +
	"\x1eOltAllowOnuRegistrationRequest\x12\x19\n" +
	"\bolt_name\x18\x01 \x01(\tR\aoltName\x12\x15\n" +
	"\x06onu_id\x18\x02 \x01(\tR\x05onuId\"c\n" +
	"\x0fOltClearRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\fdevice_state\x18\x02 \x01(\x0e2\x19.gnoi.pon.DeviceStateTypeR\vdeviceState\"b\n" +
	"\x14OltDisableOnuRequest\x12\x19\n" +
	"\bolt_name\x18\x01 \x01(\tR\aoltName\x12\x15\n" +
	"\x06onu_id\x18\x02 \x01(\tR\x05onuId\x12\x18\n" +
	"\adisable\x18\x03 \x01(\bR\adisable\"%\n" +
	"\x0fOltResetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x1dOnuClearAbortedUpgradeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"c\n" +
	"\x0fOnuClearRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\fdevice_state\x18\x02 \x01(\x0e2\x19.gnoi.pon.DeviceStateTypeR\vdeviceState\"%\n" +
	"\x0fOnuResetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\x17OltProtectionArmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03arm\x18\x02 \x01(\bR\x03arm\x12!\n" +
	"\fforce_switch\x18\x03 \x01(\bR\vforceSwitch\"0\n" +
	"\x1aOltProtectionSwitchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x19DbManagerDbRestartRequest\"'\n" +
	"%DbManagerServerStatisticsClearRequest\")\n" +
	"'DbManagerDbClientStatisticsClearRequest\"L\n" +
	"\vPonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"j\n" +
	"\x11DbManagerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*U\n" +
	"\x06FWType\x12\x17\n" +
	"\x13FW_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FW_TYPE_OLT_FIRMWARE\x10\x01\x12\x18\n" +
	"\x14FW_TYPE_ONU_FIRMWARE\x10\x02*c\n" +
	"\x0fDeviceStateType\x12\x1c\n" +
	"\x18DEVICE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEVICE_STATE_LOGS\x10\x01\x12\x1b\n" +
	"\x17DEVICE_STATE_STATISTICS\x10\x02*e\n" +
	"\x15ControllerAdminStatus\x12\x1c\n" +
	"\x18ADMIN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ADMIN_STATUS_PAUSE\x10\x01\x12\x16\n" +
	"\x12ADMIN_STATUS_START\x10\x022\xa9\n" +
	"\n" +
	"\x03Pon\x12J\n" +
	"\x0fControllerClear\x12 .gnoi.pon.ControllerClearRequest\x1a\x15.gnoi.pon.PonResponse\x12R\n" +
	"\x13ControllerSetStatus\x12$.gnoi.pon.ControllerSetStatusRequest\x1a\x15.gnoi.pon.PonResponse\x12Z\n" +
	"\x17OltAllowOnuRegistration\x12(.gnoi.pon.OltAllowOnuRegistrationRequest\x1a\x15.gnoi.pon.PonResponse\x12<\n" +
	"\bOltClear\x12\x19.gnoi.pon.OltClearRequest\x1a\x15.gnoi.pon.PonResponse\x12F\n" +
	"\rOltDisableOnu\x12\x1e.gnoi.pon.OltDisableOnuRequest\x1a\x15.gnoi.pon.PonResponse\x12<\n" +
	"\bOltReset\x12\x19.gnoi.pon.OltResetRequest\x1a\x15.gnoi.pon.PonResponse\x12X\n" +
	"\x16OnuClearAbortedUpgrade\x12'.gnoi.pon.OnuClearAbortedUpgradeRequest\x1a\x15.gnoi.pon.PonResponse\x12<\n" +
	"\bOnuClear\x12\x19.gnoi.pon.OnuClearRequest\x1a\x15.gnoi.pon.PonResponse\x12<\n" +
	"\bOnuReset\x12\x19.gnoi.pon.OnuResetRequest\x1a\x15.gnoi.pon.PonResponse\x12L\n" +
	"\x10OltProtectionArm\x12!.gnoi.pon.OltProtectionArmRequest\x1a\x15.gnoi.pon.PonResponse\x12R\n" +
	"\x13OltProtectionSwitch\x12$.gnoi.pon.OltProtectionSwitchRequest\x1a\x15.gnoi.pon.PonResponse\x12V\n" +
	"\x12DbManagerDbRestart\x12#.gnoi.pon.DbManagerDbRestartRequest\x1a\x1b.gnoi.pon.DbManagerResponse\x12n\n" +
	"\x1eDbManagerServerStatisticsClear\x12/.gnoi.pon.DbManagerServerStatisticsClearRequest\x1a\x1b.gnoi.pon.DbManagerResponse\x12r\n" +
	" DbManagerDbClientStatisticsClear\x121.gnoi.pon.DbManagerDbClientStatisticsClearRequest\x1a\x1b.gnoi.pon.DbManagerResponse\x12N\n" +
	"\x10FirmwareDownload\x12!.gnoi.pon.FirmwareDownloadRequest\x1a\x15.gnoi.pon.PonResponse(\x01\x12^\n" +
	"\x18OnuServiceConfigDownload\x12).gnoi.pon.OnuServiceConfigDownloadRequest\x1a\x15.gnoi.pon.PonResponse(\x01B(\xd2>\x050.1.0Z\x1egithub.com/openconfig/gnoi/ponb\x06proto3"

var (
	file_github_com_openconfig_gnoi_pon_pon_proto_rawDescOnce sync.Once
	file_github_com_openconfig_gnoi_pon_pon_proto_rawDescData []byte
)

func file_github_com_openconfig_gnoi_pon_pon_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_gnoi_pon_pon_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_gnoi_pon_pon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_pon_pon_proto_rawDesc), len(file_github_com_openconfig_gnoi_pon_pon_proto_rawDesc)))
	})
	return file_github_com_openconfig_gnoi_pon_pon_proto_rawDescData
}

var file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_github_com_openconfig_gnoi_pon_pon_proto_goTypes = []any{
	(FWType)(0),                                     // 0: gnoi.pon.FWType
	(DeviceStateType)(0),                            // 1: gnoi.pon.DeviceStateType
	(ControllerAdminStatus)(0),                      // 2: gnoi.pon.ControllerAdminStatus
	(*PonFilePutRequest)(nil),                       // 3: gnoi.pon.PonFilePutRequest
	(*FirmwareDownloadRequest)(nil),                 // 4: gnoi.pon.FirmwareDownloadRequest
	(*OnuServiceConfigDownloadRequest)(nil),         // 5: gnoi.pon.OnuServiceConfigDownloadRequest
	(*ControllerClearRequest)(nil),                  // 6: gnoi.pon.ControllerClearRequest
	(*ControllerSetStatusRequest)(nil),              // 7: gnoi.pon.ControllerSetStatusRequest
	(*OltAllowOnuRegistrationRequest)(nil),          // 8: gnoi.pon.OltAllowOnuRegistrationRequest
	(*OltClearRequest)(nil),                         // 9: gnoi.pon.OltClearRequest
	(*OltDisableOnuRequest)(nil),                    // 10: gnoi.pon.OltDisableOnuRequest
	(*OltResetRequest)(nil),                         // 11: gnoi.pon.OltResetRequest
	(*OnuClearAbortedUpgradeRequest)(nil),           // 12: gnoi.pon.OnuClearAbortedUpgradeRequest
	(*OnuClearRequest)(nil),                         // 13: gnoi.pon.OnuClearRequest
	(*OnuResetRequest)(nil),                         // 14: gnoi.pon.OnuResetRequest
	(*OltProtectionArmRequest)(nil),                 // 15: gnoi.pon.OltProtectionArmRequest
	(*OltProtectionSwitchRequest)(nil),              // 16: gnoi.pon.OltProtectionSwitchRequest
	(*DbManagerDbRestartRequest)(nil),               // 17: gnoi.pon.DbManagerDbRestartRequest
	(*DbManagerServerStatisticsClearRequest)(nil),   // 18: gnoi.pon.DbManagerServerStatisticsClearRequest
	(*DbManagerDbClientStatisticsClearRequest)(nil), // 19: gnoi.pon.DbManagerDbClientStatisticsClearRequest
	(*PonResponse)(nil),                             // 20: gnoi.pon.PonResponse
	(*DbManagerResponse)(nil),                       // 21: gnoi.pon.DbManagerResponse
	(*types.HashType)(nil),                          // 22: gnoi.types.HashType
}
var file_github_com_openconfig_gnoi_pon_pon_proto_depIdxs = []int32{
	22, // 0: gnoi.pon.PonFilePutRequest.hash:type_name -> gnoi.types.HashType
	0,  // 1: gnoi.pon.FirmwareDownloadRequest.fw_type:type_name -> gnoi.pon.FWType
	3,  // 2: gnoi.pon.FirmwareDownloadRequest.file_put_request:type_name -> gnoi.pon.PonFilePutRequest
	3,  // 3: gnoi.pon.OnuServiceConfigDownloadRequest.file_put_request:type_name -> gnoi.pon.PonFilePutRequest
	1,  // 4: gnoi.pon.ControllerClearRequest.device_state:type_name -> gnoi.pon.DeviceStateType
	2,  // 5: gnoi.pon.ControllerSetStatusRequest.admin_status:type_name -> gnoi.pon.ControllerAdminStatus
	1,  // 6: gnoi.pon.OltClearRequest.device_state:type_name -> gnoi.pon.DeviceStateType
	1,  // 7: gnoi.pon.OnuClearRequest.device_state:type_name -> gnoi.pon.DeviceStateType
	6,  // 8: gnoi.pon.Pon.ControllerClear:input_type -> gnoi.pon.ControllerClearRequest
	7,  // 9: gnoi.pon.Pon.ControllerSetStatus:input_type -> gnoi.pon.ControllerSetStatusRequest
	8,  // 10: gnoi.pon.Pon.OltAllowOnuRegistration:input_type -> gnoi.pon.OltAllowOnuRegistrationRequest
	9,  // 11: gnoi.pon.Pon.OltClear:input_type -> gnoi.pon.OltClearRequest
	10, // 12: gnoi.pon.Pon.OltDisableOnu:input_type -> gnoi.pon.OltDisableOnuRequest
	11, // 13: gnoi.pon.Pon.OltReset:input_type -> gnoi.pon.OltResetRequest
	12, // 14: gnoi.pon.Pon.OnuClearAbortedUpgrade:input_type -> gnoi.pon.OnuClearAbortedUpgradeRequest
	13, // 15: gnoi.pon.Pon.OnuClear:input_type -> gnoi.pon.OnuClearRequest
	14, // 16: gnoi.pon.Pon.OnuReset:input_type -> gnoi.pon.OnuResetRequest
	15, // 17: gnoi.pon.Pon.OltProtectionArm:input_type -> gnoi.pon.OltProtectionArmRequest
	16, // 18: gnoi.pon.Pon.OltProtectionSwitch:input_type -> gnoi.pon.OltProtectionSwitchRequest
	17, // 19: gnoi.pon.Pon.DbManagerDbRestart:input_type -> gnoi.pon.DbManagerDbRestartRequest
	18, // 20: gnoi.pon.Pon.DbManagerServerStatisticsClear:input_type -> gnoi.pon.DbManagerServerStatisticsClearRequest
	19, // 21: gnoi.pon.Pon.DbManagerDbClientStatisticsClear:input_type -> gnoi.pon.DbManagerDbClientStatisticsClearRequest
	4,  // 22: gnoi.pon.Pon.FirmwareDownload:input_type -> gnoi.pon.FirmwareDownloadRequest
	5,  // 23: gnoi.pon.Pon.OnuServiceConfigDownload:input_type -> gnoi.pon.OnuServiceConfigDownloadRequest
	20, // 24: gnoi.pon.Pon.ControllerClear:output_type -> gnoi.pon.PonResponse
	20, // 25: gnoi.pon.Pon.ControllerSetStatus:output_type -> gnoi.pon.PonResponse
	20, // 26: gnoi.pon.Pon.OltAllowOnuRegistration:output_type -> gnoi.pon.PonResponse
	20, // 27: gnoi.pon.Pon.OltClear:output_type -> gnoi.pon.PonResponse
	20, // 28: gnoi.pon.Pon.OltDisableOnu:output_type -> gnoi.pon.PonResponse
	20, // 29: gnoi.pon.Pon.OltReset:output_type -> gnoi.pon.PonResponse
	20, // 30: gnoi.pon.Pon.OnuClearAbortedUpgrade:output_type -> gnoi.pon.PonResponse
	20, // 31: gnoi.pon.Pon.OnuClear:output_type -> gnoi.pon.PonResponse
	20, // 32: gnoi.pon.Pon.OnuReset:output_type -> gnoi.pon.PonResponse
	20, // 33: gnoi.pon.Pon.OltProtectionArm:output_type -> gnoi.pon.PonResponse
	20, // 34: gnoi.pon.Pon.OltProtectionSwitch:output_type -> gnoi.pon.PonResponse
	21, // 35: gnoi.pon.Pon.DbManagerDbRestart:output_type -> gnoi.pon.DbManagerResponse
	21, // 36: gnoi.pon.Pon.DbManagerServerStatisticsClear:output_type -> gnoi.pon.DbManagerResponse
	21, // 37: gnoi.pon.Pon.DbManagerDbClientStatisticsClear:output_type -> gnoi.pon.DbManagerResponse
	20, // 38: gnoi.pon.Pon.FirmwareDownload:output_type -> gnoi.pon.PonResponse
	20, // 39: gnoi.pon.Pon.OnuServiceConfigDownload:output_type -> gnoi.pon.PonResponse
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_gnoi_pon_pon_proto_init() }
func file_github_com_openconfig_gnoi_pon_pon_proto_init() {
	if File_github_com_openconfig_gnoi_pon_pon_proto != nil {
		return
	}
	file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes[0].OneofWrappers = []any{
		(*PonFilePutRequest_Filename)(nil),
		(*PonFilePutRequest_Contents)(nil),
		(*PonFilePutRequest_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_pon_pon_proto_rawDesc), len(file_github_com_openconfig_gnoi_pon_pon_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_openconfig_gnoi_pon_pon_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_gnoi_pon_pon_proto_depIdxs,
		EnumInfos:         file_github_com_openconfig_gnoi_pon_pon_proto_enumTypes,
		MessageInfos:      file_github_com_openconfig_gnoi_pon_pon_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_gnoi_pon_pon_proto = out.File
	file_github_com_openconfig_gnoi_pon_pon_proto_goTypes = nil
	file_github_com_openconfig_gnoi_pon_pon_proto_depIdxs = nil
}
