// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bootz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BootzClient is the client API for Bootz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BootzClient interface {
	// GetBootConfig gets the current boot config.
	GetBootConfig(ctx context.Context, in *GetBootConfigRequest, opts ...grpc.CallOption) (*GetBootConfigResponse, error)
	// SetBootConfig replaces the existing boot config with the new provided one.
	SetBootConfig(ctx context.Context, in *SetBootConfigRequest, opts ...grpc.CallOption) (*SetBootConfigResponse, error)
}

type bootzClient struct {
	cc grpc.ClientConnInterface
}

func NewBootzClient(cc grpc.ClientConnInterface) BootzClient {
	return &bootzClient{cc}
}

func (c *bootzClient) GetBootConfig(ctx context.Context, in *GetBootConfigRequest, opts ...grpc.CallOption) (*GetBootConfigResponse, error) {
	out := new(GetBootConfigResponse)
	err := c.cc.Invoke(ctx, "/gnoi.bootz.Bootz/GetBootConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootzClient) SetBootConfig(ctx context.Context, in *SetBootConfigRequest, opts ...grpc.CallOption) (*SetBootConfigResponse, error) {
	out := new(SetBootConfigResponse)
	err := c.cc.Invoke(ctx, "/gnoi.bootz.Bootz/SetBootConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootzServer is the server API for Bootz service.
// All implementations must embed UnimplementedBootzServer
// for forward compatibility
type BootzServer interface {
	// GetBootConfig gets the current boot config.
	GetBootConfig(context.Context, *GetBootConfigRequest) (*GetBootConfigResponse, error)
	// SetBootConfig replaces the existing boot config with the new provided one.
	SetBootConfig(context.Context, *SetBootConfigRequest) (*SetBootConfigResponse, error)
	mustEmbedUnimplementedBootzServer()
}

// UnimplementedBootzServer must be embedded to have forward compatible implementations.
type UnimplementedBootzServer struct {
}

func (UnimplementedBootzServer) GetBootConfig(context.Context, *GetBootConfigRequest) (*GetBootConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBootConfig not implemented")
}
func (UnimplementedBootzServer) SetBootConfig(context.Context, *SetBootConfigRequest) (*SetBootConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBootConfig not implemented")
}
func (UnimplementedBootzServer) mustEmbedUnimplementedBootzServer() {}

// UnsafeBootzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootzServer will
// result in compilation errors.
type UnsafeBootzServer interface {
	mustEmbedUnimplementedBootzServer()
}

func RegisterBootzServer(s grpc.ServiceRegistrar, srv BootzServer) {
	s.RegisterService(&Bootz_ServiceDesc, srv)
}

func _Bootz_GetBootConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzServer).GetBootConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.bootz.Bootz/GetBootConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzServer).GetBootConfig(ctx, req.(*GetBootConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootz_SetBootConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzServer).SetBootConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.bootz.Bootz/SetBootConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzServer).SetBootConfig(ctx, req.(*SetBootConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bootz_ServiceDesc is the grpc.ServiceDesc for Bootz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bootz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.bootz.Bootz",
	HandlerType: (*BootzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBootConfig",
			Handler:    _Bootz_GetBootConfig_Handler,
		},
		{
			MethodName: "SetBootConfig",
			Handler:    _Bootz_SetBootConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bootz/bootz.proto",
}
