//
// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: bootz/bootz.proto

package bootz

import (
	bootz "github.com/openconfig/bootz/proto/bootz"
	_ "github.com/openconfig/gnoi/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// It is safe to assume that gNOI service is hosted on the primary Controller
// Card, and the boot config is synced automatically between primary and
// secondary Controller Cards. Therefore, we don't need to specify the
// Controller Card ID.
type GetBootConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBootConfigRequest) Reset() {
	*x = GetBootConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootz_bootz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBootConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootConfigRequest) ProtoMessage() {}

func (x *GetBootConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootz_bootz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBootConfigRequest) Descriptor() ([]byte, []int) {
	return file_bootz_bootz_proto_rawDescGZIP(), []int{0}
}

type GetBootConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BootConfig *bootz.BootConfig `protobuf:"bytes,1,opt,name=boot_config,json=bootConfig,proto3" json:"boot_config,omitempty"`
}

func (x *GetBootConfigResponse) Reset() {
	*x = GetBootConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootz_bootz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBootConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootConfigResponse) ProtoMessage() {}

func (x *GetBootConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootz_bootz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootConfigResponse.ProtoReflect.Descriptor instead.
func (*GetBootConfigResponse) Descriptor() ([]byte, []int) {
	return file_bootz_bootz_proto_rawDescGZIP(), []int{1}
}

func (x *GetBootConfigResponse) GetBootConfig() *bootz.BootConfig {
	if x != nil {
		return x.BootConfig
	}
	return nil
}

type SetBootConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BootConfig *bootz.BootConfig `protobuf:"bytes,1,opt,name=boot_config,json=bootConfig,proto3" json:"boot_config,omitempty"`
}

func (x *SetBootConfigRequest) Reset() {
	*x = SetBootConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootz_bootz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBootConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootConfigRequest) ProtoMessage() {}

func (x *SetBootConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootz_bootz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootConfigRequest.ProtoReflect.Descriptor instead.
func (*SetBootConfigRequest) Descriptor() ([]byte, []int) {
	return file_bootz_bootz_proto_rawDescGZIP(), []int{2}
}

func (x *SetBootConfigRequest) GetBootConfig() *bootz.BootConfig {
	if x != nil {
		return x.BootConfig
	}
	return nil
}

type SetBootConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBootConfigResponse) Reset() {
	*x = SetBootConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootz_bootz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBootConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootConfigResponse) ProtoMessage() {}

func (x *SetBootConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootz_bootz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootConfigResponse.ProtoReflect.Descriptor instead.
func (*SetBootConfigResponse) Descriptor() ([]byte, []int) {
	return file_bootz_bootz_proto_rawDescGZIP(), []int{3}
}

var File_bootz_bootz_proto protoreflect.FileDescriptor

var file_bootz_bootz_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x1a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e, 0x6f, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x0b, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x62, 0x6f, 0x6f,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x50, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x38, 0x0a, 0x0b, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x62,
	0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xb7, 0x01, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x74, 0x7a, 0x12, 0x56, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x2e,
	0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x62, 0x6f, 0x6f,
	0x74, 0x7a, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x62,
	0x6f, 0x6f, 0x74, 0x7a, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0xd2, 0x3e,
	0x05, 0x30, 0x2e, 0x31, 0x2e, 0x30, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e,
	0x6f, 0x69, 0x2f, 0x62, 0x6f, 0x6f, 0x74, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bootz_bootz_proto_rawDescOnce sync.Once
	file_bootz_bootz_proto_rawDescData = file_bootz_bootz_proto_rawDesc
)

func file_bootz_bootz_proto_rawDescGZIP() []byte {
	file_bootz_bootz_proto_rawDescOnce.Do(func() {
		file_bootz_bootz_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootz_bootz_proto_rawDescData)
	})
	return file_bootz_bootz_proto_rawDescData
}

var file_bootz_bootz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bootz_bootz_proto_goTypes = []interface{}{
	(*GetBootConfigRequest)(nil),  // 0: gnoi.bootz.GetBootConfigRequest
	(*GetBootConfigResponse)(nil), // 1: gnoi.bootz.GetBootConfigResponse
	(*SetBootConfigRequest)(nil),  // 2: gnoi.bootz.SetBootConfigRequest
	(*SetBootConfigResponse)(nil), // 3: gnoi.bootz.SetBootConfigResponse
	(*bootz.BootConfig)(nil),      // 4: bootz.proto.BootConfig
}
var file_bootz_bootz_proto_depIdxs = []int32{
	4, // 0: gnoi.bootz.GetBootConfigResponse.boot_config:type_name -> bootz.proto.BootConfig
	4, // 1: gnoi.bootz.SetBootConfigRequest.boot_config:type_name -> bootz.proto.BootConfig
	0, // 2: gnoi.bootz.Bootz.GetBootConfig:input_type -> gnoi.bootz.GetBootConfigRequest
	2, // 3: gnoi.bootz.Bootz.SetBootConfig:input_type -> gnoi.bootz.SetBootConfigRequest
	1, // 4: gnoi.bootz.Bootz.GetBootConfig:output_type -> gnoi.bootz.GetBootConfigResponse
	3, // 5: gnoi.bootz.Bootz.SetBootConfig:output_type -> gnoi.bootz.SetBootConfigResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bootz_bootz_proto_init() }
func file_bootz_bootz_proto_init() {
	if File_bootz_bootz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bootz_bootz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBootConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootz_bootz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBootConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootz_bootz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBootConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootz_bootz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBootConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootz_bootz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootz_bootz_proto_goTypes,
		DependencyIndexes: file_bootz_bootz_proto_depIdxs,
		MessageInfos:      file_bootz_bootz_proto_msgTypes,
	}.Build()
	File_bootz_bootz_proto = out.File
	file_bootz_bootz_proto_rawDesc = nil
	file_bootz_bootz_proto_goTypes = nil
	file_bootz_bootz_proto_depIdxs = nil
}
