// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/gnoi/system/system.proto

/*
Package gnoi_system is a generated protocol buffer package.

It is generated from these files:
	github.com/openconfig/gnoi/system/system.proto

It has these top-level messages:
	SwitchControlProcessorRequest
	SwitchControlProcessorResponse
	RebootRequest
	RebootResponse
	CancelRebootRequest
	CancelRebootResponse
	RebootStatusRequest
	RebootStatusResponse
	TimeRequest
	TimeResponse
	PingRequest
	PingResponse
	TracerouteRequest
	TracerouteResponse
	Package
	SetPackageRequest
	SetPackageResponse
*/
package gnoi_system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gnoi "github.com/openconfig/gnoi"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A RebootMethod determines what should be done with a target when a Reboot is
// requested.  Only the COLD method is required to be supported by all
// targets.  Methods the target does not support should result in failure.
//
// It is vendor defined if a WARM reboot is the same as an NSF reboot.
type RebootMethod int32

const (
	RebootMethod_UNKNOWN   RebootMethod = 0
	RebootMethod_COLD      RebootMethod = 1
	RebootMethod_POWERDOWN RebootMethod = 2
	RebootMethod_HALT      RebootMethod = 3
	RebootMethod_WARM      RebootMethod = 4
	RebootMethod_NSF       RebootMethod = 5
	RebootMethod_RESET     RebootMethod = 6
	RebootMethod_POWERUP   RebootMethod = 7
)

var RebootMethod_name = map[int32]string{
	0: "UNKNOWN",
	1: "COLD",
	2: "POWERDOWN",
	3: "HALT",
	4: "WARM",
	5: "NSF",
	6: "RESET",
	7: "POWERUP",
}
var RebootMethod_value = map[string]int32{
	"UNKNOWN":   0,
	"COLD":      1,
	"POWERDOWN": 2,
	"HALT":      3,
	"WARM":      4,
	"NSF":       5,
	"RESET":     6,
	"POWERUP":   7,
}

func (x RebootMethod) String() string {
	return proto.EnumName(RebootMethod_name, int32(x))
}
func (RebootMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TracerouteRequest_L4Protocol int32

const (
	TracerouteRequest_ICMP TracerouteRequest_L4Protocol = 0
	TracerouteRequest_TCP  TracerouteRequest_L4Protocol = 1
	TracerouteRequest_UDP  TracerouteRequest_L4Protocol = 2
)

var TracerouteRequest_L4Protocol_name = map[int32]string{
	0: "ICMP",
	1: "TCP",
	2: "UDP",
}
var TracerouteRequest_L4Protocol_value = map[string]int32{
	"ICMP": 0,
	"TCP":  1,
	"UDP":  2,
}

func (x TracerouteRequest_L4Protocol) String() string {
	return proto.EnumName(TracerouteRequest_L4Protocol_name, int32(x))
}
func (TracerouteRequest_L4Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

// State is the resulting state of a single traceoroute packet.
type TracerouteResponse_State int32

const (
	TracerouteResponse_DEFAULT              TracerouteResponse_State = 0
	TracerouteResponse_NONE                 TracerouteResponse_State = 1
	TracerouteResponse_UNKNOWN              TracerouteResponse_State = 2
	TracerouteResponse_ICMP                 TracerouteResponse_State = 3
	TracerouteResponse_HOST_UNREACHABLE     TracerouteResponse_State = 4
	TracerouteResponse_NETWORK_UNREACHABLE  TracerouteResponse_State = 5
	TracerouteResponse_PROTOCOL_UNREACHABLE TracerouteResponse_State = 6
	TracerouteResponse_SOURCE_ROUTE_FAILED  TracerouteResponse_State = 7
	TracerouteResponse_FRAGMENTATION_NEEDED TracerouteResponse_State = 8
	TracerouteResponse_PROHIBITED           TracerouteResponse_State = 9
	TracerouteResponse_PRECEDENCE_VIOLATION TracerouteResponse_State = 10
	TracerouteResponse_PRECEDENCE_CUTOFF    TracerouteResponse_State = 11
)

var TracerouteResponse_State_name = map[int32]string{
	0:  "DEFAULT",
	1:  "NONE",
	2:  "UNKNOWN",
	3:  "ICMP",
	4:  "HOST_UNREACHABLE",
	5:  "NETWORK_UNREACHABLE",
	6:  "PROTOCOL_UNREACHABLE",
	7:  "SOURCE_ROUTE_FAILED",
	8:  "FRAGMENTATION_NEEDED",
	9:  "PROHIBITED",
	10: "PRECEDENCE_VIOLATION",
	11: "PRECEDENCE_CUTOFF",
}
var TracerouteResponse_State_value = map[string]int32{
	"DEFAULT":              0,
	"NONE":                 1,
	"UNKNOWN":              2,
	"ICMP":                 3,
	"HOST_UNREACHABLE":     4,
	"NETWORK_UNREACHABLE":  5,
	"PROTOCOL_UNREACHABLE": 6,
	"SOURCE_ROUTE_FAILED":  7,
	"FRAGMENTATION_NEEDED": 8,
	"PROHIBITED":           9,
	"PRECEDENCE_VIOLATION": 10,
	"PRECEDENCE_CUTOFF":    11,
}

func (x TracerouteResponse_State) String() string {
	return proto.EnumName(TracerouteResponse_State_name, int32(x))
}
func (TracerouteResponse_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

type SwitchControlProcessorRequest struct {
	ControlProcessor *gnoi.Path `protobuf:"bytes,1,opt,name=control_processor,json=controlProcessor" json:"control_processor,omitempty"`
}

func (m *SwitchControlProcessorRequest) Reset()                    { *m = SwitchControlProcessorRequest{} }
func (m *SwitchControlProcessorRequest) String() string            { return proto.CompactTextString(m) }
func (*SwitchControlProcessorRequest) ProtoMessage()               {}
func (*SwitchControlProcessorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SwitchControlProcessorRequest) GetControlProcessor() *gnoi.Path {
	if m != nil {
		return m.ControlProcessor
	}
	return nil
}

type SwitchControlProcessorResponse struct {
	ControlProcessor *gnoi.Path `protobuf:"bytes,1,opt,name=control_processor,json=controlProcessor" json:"control_processor,omitempty"`
	Version          string     `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Uptime           int64      `protobuf:"varint,3,opt,name=uptime" json:"uptime,omitempty"`
}

func (m *SwitchControlProcessorResponse) Reset()                    { *m = SwitchControlProcessorResponse{} }
func (m *SwitchControlProcessorResponse) String() string            { return proto.CompactTextString(m) }
func (*SwitchControlProcessorResponse) ProtoMessage()               {}
func (*SwitchControlProcessorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SwitchControlProcessorResponse) GetControlProcessor() *gnoi.Path {
	if m != nil {
		return m.ControlProcessor
	}
	return nil
}

func (m *SwitchControlProcessorResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SwitchControlProcessorResponse) GetUptime() int64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

// A RebootRequest requests the specified target be rebooted using the specified
// method aftar the specified delay.  Only the DEFAULT method with a delay of 0
// is guaranteed to be accepted for all target types.
type RebootRequest struct {
	Method RebootMethod `protobuf:"varint,1,opt,name=method,enum=gnoi.system.RebootMethod" json:"method,omitempty"`
	// Delay in nanoseconds before issuing reboot.
	Delay uint64 `protobuf:"varint,2,opt,name=delay" json:"delay,omitempty"`
	// Informational reason for the reboot.
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	// Optional sub-components to reboot.
	Subcomponents []*gnoi.Path `protobuf:"bytes,4,rep,name=subcomponents" json:"subcomponents,omitempty"`
	// Force reboot if sanity checks fail. (ex. uncommited configuration)
	Force bool `protobuf:"varint,5,opt,name=force" json:"force,omitempty"`
}

func (m *RebootRequest) Reset()                    { *m = RebootRequest{} }
func (m *RebootRequest) String() string            { return proto.CompactTextString(m) }
func (*RebootRequest) ProtoMessage()               {}
func (*RebootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RebootRequest) GetMethod() RebootMethod {
	if m != nil {
		return m.Method
	}
	return RebootMethod_UNKNOWN
}

func (m *RebootRequest) GetDelay() uint64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *RebootRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RebootRequest) GetSubcomponents() []*gnoi.Path {
	if m != nil {
		return m.Subcomponents
	}
	return nil
}

func (m *RebootRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type RebootResponse struct {
}

func (m *RebootResponse) Reset()                    { *m = RebootResponse{} }
func (m *RebootResponse) String() string            { return proto.CompactTextString(m) }
func (*RebootResponse) ProtoMessage()               {}
func (*RebootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// A CancelRebootRequest requests the cancelation of any outstanding reboot
// request.
type CancelRebootRequest struct {
	Message       string       `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Subcomponents []*gnoi.Path `protobuf:"bytes,2,rep,name=subcomponents" json:"subcomponents,omitempty"`
}

func (m *CancelRebootRequest) Reset()                    { *m = CancelRebootRequest{} }
func (m *CancelRebootRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelRebootRequest) ProtoMessage()               {}
func (*CancelRebootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CancelRebootRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CancelRebootRequest) GetSubcomponents() []*gnoi.Path {
	if m != nil {
		return m.Subcomponents
	}
	return nil
}

type CancelRebootResponse struct {
}

func (m *CancelRebootResponse) Reset()                    { *m = CancelRebootResponse{} }
func (m *CancelRebootResponse) String() string            { return proto.CompactTextString(m) }
func (*CancelRebootResponse) ProtoMessage()               {}
func (*CancelRebootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RebootStatusRequest struct {
	Subcomponents []*gnoi.Path `protobuf:"bytes,1,rep,name=subcomponents" json:"subcomponents,omitempty"`
}

func (m *RebootStatusRequest) Reset()                    { *m = RebootStatusRequest{} }
func (m *RebootStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*RebootStatusRequest) ProtoMessage()               {}
func (*RebootStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RebootStatusRequest) GetSubcomponents() []*gnoi.Path {
	if m != nil {
		return m.Subcomponents
	}
	return nil
}

type RebootStatusResponse struct {
	Active bool   `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
	Wait   uint64 `protobuf:"varint,2,opt,name=wait" json:"wait,omitempty"`
	When   uint64 `protobuf:"varint,3,opt,name=when" json:"when,omitempty"`
	Reason string `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
	Count  uint32 `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *RebootStatusResponse) Reset()                    { *m = RebootStatusResponse{} }
func (m *RebootStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*RebootStatusResponse) ProtoMessage()               {}
func (*RebootStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RebootStatusResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *RebootStatusResponse) GetWait() uint64 {
	if m != nil {
		return m.Wait
	}
	return 0
}

func (m *RebootStatusResponse) GetWhen() uint64 {
	if m != nil {
		return m.When
	}
	return 0
}

func (m *RebootStatusResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *RebootStatusResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// A TimeRequest requests the current time accodring to the target.
type TimeRequest struct {
}

func (m *TimeRequest) Reset()                    { *m = TimeRequest{} }
func (m *TimeRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeRequest) ProtoMessage()               {}
func (*TimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type TimeResponse struct {
	Time uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *TimeResponse) Reset()                    { *m = TimeResponse{} }
func (m *TimeResponse) String() string            { return proto.CompactTextString(m) }
func (*TimeResponse) ProtoMessage()               {}
func (*TimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TimeResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// A PingRequest describes the ping operation to perform.  Only the destination
// fields is required.  Any field not specified is set to a reasonable server
// specified value.  Not all fields are supported by all vendors.
//
// A count of 0 defaults to a vendor specified value, typically 5.  A count of
// -1 means continue until the RPC times out or is canceled.
//
// If the interval is -1 then a flood ping is issued.
//
// If the size is 0, the vendor default size will be used (typically 56 bytes).
type PingRequest struct {
	Destination   string          `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Source        string          `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Count         int32           `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Interval      int64           `protobuf:"varint,4,opt,name=interval" json:"interval,omitempty"`
	Wait          int64           `protobuf:"varint,5,opt,name=wait" json:"wait,omitempty"`
	Size          int32           `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	DoNotFragment bool            `protobuf:"varint,7,opt,name=do_not_fragment,json=doNotFragment" json:"do_not_fragment,omitempty"`
	DoNotResolve  bool            `protobuf:"varint,8,opt,name=do_not_resolve,json=doNotResolve" json:"do_not_resolve,omitempty"`
	L3Protocol    gnoi.L3Protocol `protobuf:"varint,9,opt,name=l3protocol,enum=gnoi.L3Protocol" json:"l3protocol,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PingRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *PingRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *PingRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PingRequest) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *PingRequest) GetWait() int64 {
	if m != nil {
		return m.Wait
	}
	return 0
}

func (m *PingRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PingRequest) GetDoNotFragment() bool {
	if m != nil {
		return m.DoNotFragment
	}
	return false
}

func (m *PingRequest) GetDoNotResolve() bool {
	if m != nil {
		return m.DoNotResolve
	}
	return false
}

func (m *PingRequest) GetL3Protocol() gnoi.L3Protocol {
	if m != nil {
		return m.L3Protocol
	}
	return gnoi.L3Protocol_UNSPECIFIED
}

// A PingResponse represents either the reponse to a single ping packet
// (the bytes field is non-zero) or the summary statistics (sent is non-zero).
//
// For a single ping packet, time is the round trip time, in nanoseconds.  For
// summary statistics, it is the time spent by the ping operation.  The time is
// not always present in summary statistics.  The std_dev is not always present
// in summary statistics.
type PingResponse struct {
	Source   string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Time     int64  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Sent     int32  `protobuf:"varint,3,opt,name=sent" json:"sent,omitempty"`
	Received int32  `protobuf:"varint,4,opt,name=received" json:"received,omitempty"`
	MinTime  int64  `protobuf:"varint,5,opt,name=min_time,json=minTime" json:"min_time,omitempty"`
	AvgTime  int64  `protobuf:"varint,6,opt,name=avg_time,json=avgTime" json:"avg_time,omitempty"`
	MaxTime  int64  `protobuf:"varint,7,opt,name=max_time,json=maxTime" json:"max_time,omitempty"`
	StdDev   int64  `protobuf:"varint,8,opt,name=std_dev,json=stdDev" json:"std_dev,omitempty"`
	Bytes    int32  `protobuf:"varint,11,opt,name=bytes" json:"bytes,omitempty"`
	Sequence int32  `protobuf:"varint,12,opt,name=sequence" json:"sequence,omitempty"`
	Ttl      int32  `protobuf:"varint,13,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PingResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *PingResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PingResponse) GetSent() int32 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *PingResponse) GetReceived() int32 {
	if m != nil {
		return m.Received
	}
	return 0
}

func (m *PingResponse) GetMinTime() int64 {
	if m != nil {
		return m.MinTime
	}
	return 0
}

func (m *PingResponse) GetAvgTime() int64 {
	if m != nil {
		return m.AvgTime
	}
	return 0
}

func (m *PingResponse) GetMaxTime() int64 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

func (m *PingResponse) GetStdDev() int64 {
	if m != nil {
		return m.StdDev
	}
	return 0
}

func (m *PingResponse) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *PingResponse) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PingResponse) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

// A TracerouteRequest describes the traceroute operation to perform.  Only the
// destination field is required.  Any field not specified is set to a
// reasonable server specified value.  Not all fields are supported by all
// vendors.
//
// If the hop_count is -1 the traceroute will continue forever.
//
type TracerouteRequest struct {
	Source        string                       `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Destination   string                       `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	InitialTtl    uint32                       `protobuf:"varint,3,opt,name=initial_ttl,json=initialTtl" json:"initial_ttl,omitempty"`
	MaxTtl        int32                        `protobuf:"varint,4,opt,name=max_ttl,json=maxTtl" json:"max_ttl,omitempty"`
	Wait          int64                        `protobuf:"varint,5,opt,name=wait" json:"wait,omitempty"`
	DoNotFragment bool                         `protobuf:"varint,6,opt,name=do_not_fragment,json=doNotFragment" json:"do_not_fragment,omitempty"`
	DoNotResolve  bool                         `protobuf:"varint,7,opt,name=do_not_resolve,json=doNotResolve" json:"do_not_resolve,omitempty"`
	L3Protocol    gnoi.L3Protocol              `protobuf:"varint,8,opt,name=l3protocol,enum=gnoi.L3Protocol" json:"l3protocol,omitempty"`
	L4Protocol    TracerouteRequest_L4Protocol `protobuf:"varint,9,opt,name=l4protocol,enum=gnoi.system.TracerouteRequest_L4Protocol" json:"l4protocol,omitempty"`
}

func (m *TracerouteRequest) Reset()                    { *m = TracerouteRequest{} }
func (m *TracerouteRequest) String() string            { return proto.CompactTextString(m) }
func (*TracerouteRequest) ProtoMessage()               {}
func (*TracerouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TracerouteRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TracerouteRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *TracerouteRequest) GetInitialTtl() uint32 {
	if m != nil {
		return m.InitialTtl
	}
	return 0
}

func (m *TracerouteRequest) GetMaxTtl() int32 {
	if m != nil {
		return m.MaxTtl
	}
	return 0
}

func (m *TracerouteRequest) GetWait() int64 {
	if m != nil {
		return m.Wait
	}
	return 0
}

func (m *TracerouteRequest) GetDoNotFragment() bool {
	if m != nil {
		return m.DoNotFragment
	}
	return false
}

func (m *TracerouteRequest) GetDoNotResolve() bool {
	if m != nil {
		return m.DoNotResolve
	}
	return false
}

func (m *TracerouteRequest) GetL3Protocol() gnoi.L3Protocol {
	if m != nil {
		return m.L3Protocol
	}
	return gnoi.L3Protocol_UNSPECIFIED
}

func (m *TracerouteRequest) GetL4Protocol() TracerouteRequest_L4Protocol {
	if m != nil {
		return m.L4Protocol
	}
	return TracerouteRequest_ICMP
}

// A TraceRouteResponse contains the result of a single traceoute packet.
//
// There may be an optional initial response that provides information about the
// traceroute request itself and contains at least one of the fields in the the
// initial block of fields and none of the fields following that block.  All
// subsequent responses should not contain any of these fields.
//
// Typically multiple responses are received for each hop, as the packets are
// received.
//
// The mpls field maps names to values.  Example names include "Label", "CoS",
// "TTL", "S", and "MRU".
// [Perhaps we should list the canonical names that must be used when
// applicable].
type TracerouteResponse struct {
	// The following fields are only filled in for the first message.
	// If any of these fields are specified, all fields following this
	// block are left unspecified.
	DestinationName    string `protobuf:"bytes,1,opt,name=destination_name,json=destinationName" json:"destination_name,omitempty"`
	DestinationAddress string `protobuf:"bytes,2,opt,name=destination_address,json=destinationAddress" json:"destination_address,omitempty"`
	Hops               int32  `protobuf:"varint,3,opt,name=hops" json:"hops,omitempty"`
	PacketSize         int32  `protobuf:"varint,4,opt,name=packet_size,json=packetSize" json:"packet_size,omitempty"`
	// The following fields provide the disposition of a single traceroute
	// packet.
	Hop      int32                    `protobuf:"varint,5,opt,name=hop" json:"hop,omitempty"`
	Address  string                   `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
	Name     string                   `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	Rtt      int64                    `protobuf:"varint,8,opt,name=rtt" json:"rtt,omitempty"`
	State    TracerouteResponse_State `protobuf:"varint,9,opt,name=state,enum=gnoi.system.TracerouteResponse_State" json:"state,omitempty"`
	IcmpCode int32                    `protobuf:"varint,10,opt,name=icmp_code,json=icmpCode" json:"icmp_code,omitempty"`
	Mpls     map[string]string        `protobuf:"bytes,11,rep,name=mpls" json:"mpls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AsPath   []int32                  `protobuf:"varint,12,rep,packed,name=as_path,json=asPath" json:"as_path,omitempty"`
}

func (m *TracerouteResponse) Reset()                    { *m = TracerouteResponse{} }
func (m *TracerouteResponse) String() string            { return proto.CompactTextString(m) }
func (*TracerouteResponse) ProtoMessage()               {}
func (*TracerouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TracerouteResponse) GetDestinationName() string {
	if m != nil {
		return m.DestinationName
	}
	return ""
}

func (m *TracerouteResponse) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *TracerouteResponse) GetHops() int32 {
	if m != nil {
		return m.Hops
	}
	return 0
}

func (m *TracerouteResponse) GetPacketSize() int32 {
	if m != nil {
		return m.PacketSize
	}
	return 0
}

func (m *TracerouteResponse) GetHop() int32 {
	if m != nil {
		return m.Hop
	}
	return 0
}

func (m *TracerouteResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TracerouteResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TracerouteResponse) GetRtt() int64 {
	if m != nil {
		return m.Rtt
	}
	return 0
}

func (m *TracerouteResponse) GetState() TracerouteResponse_State {
	if m != nil {
		return m.State
	}
	return TracerouteResponse_DEFAULT
}

func (m *TracerouteResponse) GetIcmpCode() int32 {
	if m != nil {
		return m.IcmpCode
	}
	return 0
}

func (m *TracerouteResponse) GetMpls() map[string]string {
	if m != nil {
		return m.Mpls
	}
	return nil
}

func (m *TracerouteResponse) GetAsPath() []int32 {
	if m != nil {
		return m.AsPath
	}
	return nil
}

// Package defines a single package file to be placed on the target.
type Package struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Version  string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	Activate bool   `protobuf:"varint,5,opt,name=activate" json:"activate,omitempty"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Package) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Package) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Package) GetActivate() bool {
	if m != nil {
		return m.Activate
	}
	return false
}

// SetPackageRequest will place the package onto the target and optionally mark
// it as the next bootable image. The initial message must be a package
// message containing the filename and information about the file. Following the
// initial message the contents are then streamed in maximum 64k chunks. The
// final message must be a hash message contains the hash of the file contents.
type SetPackageRequest struct {
	// Types that are valid to be assigned to Request:
	//	*SetPackageRequest_Package
	//	*SetPackageRequest_Contents
	//	*SetPackageRequest_Hash
	Request isSetPackageRequest_Request `protobuf_oneof:"request"`
}

func (m *SetPackageRequest) Reset()                    { *m = SetPackageRequest{} }
func (m *SetPackageRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPackageRequest) ProtoMessage()               {}
func (*SetPackageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type isSetPackageRequest_Request interface {
	isSetPackageRequest_Request()
}

type SetPackageRequest_Package struct {
	Package *Package `protobuf:"bytes,1,opt,name=package,oneof"`
}
type SetPackageRequest_Contents struct {
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3,oneof"`
}
type SetPackageRequest_Hash struct {
	Hash *gnoi.HashType `protobuf:"bytes,3,opt,name=hash,oneof"`
}

func (*SetPackageRequest_Package) isSetPackageRequest_Request()  {}
func (*SetPackageRequest_Contents) isSetPackageRequest_Request() {}
func (*SetPackageRequest_Hash) isSetPackageRequest_Request()     {}

func (m *SetPackageRequest) GetRequest() isSetPackageRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SetPackageRequest) GetPackage() *Package {
	if x, ok := m.GetRequest().(*SetPackageRequest_Package); ok {
		return x.Package
	}
	return nil
}

func (m *SetPackageRequest) GetContents() []byte {
	if x, ok := m.GetRequest().(*SetPackageRequest_Contents); ok {
		return x.Contents
	}
	return nil
}

func (m *SetPackageRequest) GetHash() *gnoi.HashType {
	if x, ok := m.GetRequest().(*SetPackageRequest_Hash); ok {
		return x.Hash
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SetPackageRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SetPackageRequest_OneofMarshaler, _SetPackageRequest_OneofUnmarshaler, _SetPackageRequest_OneofSizer, []interface{}{
		(*SetPackageRequest_Package)(nil),
		(*SetPackageRequest_Contents)(nil),
		(*SetPackageRequest_Hash)(nil),
	}
}

func _SetPackageRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SetPackageRequest)
	// request
	switch x := m.Request.(type) {
	case *SetPackageRequest_Package:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Package); err != nil {
			return err
		}
	case *SetPackageRequest_Contents:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Contents)
	case *SetPackageRequest_Hash:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hash); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SetPackageRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _SetPackageRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SetPackageRequest)
	switch tag {
	case 1: // request.package
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Package)
		err := b.DecodeMessage(msg)
		m.Request = &SetPackageRequest_Package{msg}
		return true, err
	case 2: // request.contents
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Request = &SetPackageRequest_Contents{x}
		return true, err
	case 3: // request.hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(gnoi.HashType)
		err := b.DecodeMessage(msg)
		m.Request = &SetPackageRequest_Hash{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SetPackageRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SetPackageRequest)
	// request
	switch x := m.Request.(type) {
	case *SetPackageRequest_Package:
		s := proto.Size(x.Package)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SetPackageRequest_Contents:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Contents)))
		n += len(x.Contents)
	case *SetPackageRequest_Hash:
		s := proto.Size(x.Hash)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetPackageResponse struct {
}

func (m *SetPackageResponse) Reset()                    { *m = SetPackageResponse{} }
func (m *SetPackageResponse) String() string            { return proto.CompactTextString(m) }
func (*SetPackageResponse) ProtoMessage()               {}
func (*SetPackageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*SwitchControlProcessorRequest)(nil), "gnoi.system.SwitchControlProcessorRequest")
	proto.RegisterType((*SwitchControlProcessorResponse)(nil), "gnoi.system.SwitchControlProcessorResponse")
	proto.RegisterType((*RebootRequest)(nil), "gnoi.system.RebootRequest")
	proto.RegisterType((*RebootResponse)(nil), "gnoi.system.RebootResponse")
	proto.RegisterType((*CancelRebootRequest)(nil), "gnoi.system.CancelRebootRequest")
	proto.RegisterType((*CancelRebootResponse)(nil), "gnoi.system.CancelRebootResponse")
	proto.RegisterType((*RebootStatusRequest)(nil), "gnoi.system.RebootStatusRequest")
	proto.RegisterType((*RebootStatusResponse)(nil), "gnoi.system.RebootStatusResponse")
	proto.RegisterType((*TimeRequest)(nil), "gnoi.system.TimeRequest")
	proto.RegisterType((*TimeResponse)(nil), "gnoi.system.TimeResponse")
	proto.RegisterType((*PingRequest)(nil), "gnoi.system.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "gnoi.system.PingResponse")
	proto.RegisterType((*TracerouteRequest)(nil), "gnoi.system.TracerouteRequest")
	proto.RegisterType((*TracerouteResponse)(nil), "gnoi.system.TracerouteResponse")
	proto.RegisterType((*Package)(nil), "gnoi.system.Package")
	proto.RegisterType((*SetPackageRequest)(nil), "gnoi.system.SetPackageRequest")
	proto.RegisterType((*SetPackageResponse)(nil), "gnoi.system.SetPackageResponse")
	proto.RegisterEnum("gnoi.system.RebootMethod", RebootMethod_name, RebootMethod_value)
	proto.RegisterEnum("gnoi.system.TracerouteRequest_L4Protocol", TracerouteRequest_L4Protocol_name, TracerouteRequest_L4Protocol_value)
	proto.RegisterEnum("gnoi.system.TracerouteResponse_State", TracerouteResponse_State_name, TracerouteResponse_State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for System service

type SystemClient interface {
	// Ping executes the ping command on the target and streams back
	// the results.  Some targets may not stream any results until all
	// results are in.  If a packet count is not explicitly provided,
	// 5 is used.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (System_PingClient, error)
	// Traceroute executes the traceroute command on the target and streams back
	// the results.  Some targets may not stream any results until all
	// results are in.  If a hop count is not explicitly provided,
	// 30 is used.
	Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (System_TracerouteClient, error)
	// Time returns the current time on the target.  Time is typically used to
	// test if a target is actually responding.
	Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
	// SetPackage places a software package (possibly including bootable images)
	// on the target. The file is sent in sequential messages, each message
	// up to 64KB of data. A final message must be sent that includes the hash
	// of the data sent. An error is returned if the location does not exist or
	// there is an error writing the data. If no checksum is received, the target
	// must assume the operation is incomplete and remove the partially
	// transmitted file. The target should initially write the file to a temporary location so a failure
	// does not destroy the original file.
	SetPackage(ctx context.Context, opts ...grpc.CallOption) (System_SetPackageClient, error)
	// SwitchControlProcessor will switch from the current route processor to the
	// provided route processor. If the current route processor is the same as the
	// one provided it is a NOOP. If the target does not exist an error is
	// returned.
	SwitchControlProcessor(ctx context.Context, in *SwitchControlProcessorRequest, opts ...grpc.CallOption) (*SwitchControlProcessorResponse, error)
	// Reboot causes the target to reboot, possibly at some point in the future.
	// If the method of reboot is not supported then the Reboot RPC will fail.
	// If the reboot is immediate the command will block until the subcomponents
	// have restarted.
	// If a reboot on the active control processor is pending the service must
	// reject all other reboot requests.
	// If a reboot request for active control processor is initiated with other
	// pending reboot requests it must be rejected.
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error)
	// RebootStatus returns the status of reboot for the target.
	RebootStatus(ctx context.Context, in *RebootStatusRequest, opts ...grpc.CallOption) (*RebootStatusResponse, error)
	// CancelReboot cancels any pending reboot request.
	CancelReboot(ctx context.Context, in *CancelRebootRequest, opts ...grpc.CallOption) (*CancelRebootResponse, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (System_PingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_System_serviceDesc.Streams[0], c.cc, "/gnoi.system.System/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &systemPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type System_PingClient interface {
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type systemPingClient struct {
	grpc.ClientStream
}

func (x *systemPingClient) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *systemClient) Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (System_TracerouteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_System_serviceDesc.Streams[1], c.cc, "/gnoi.system.System/Traceroute", opts...)
	if err != nil {
		return nil, err
	}
	x := &systemTracerouteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type System_TracerouteClient interface {
	Recv() (*TracerouteResponse, error)
	grpc.ClientStream
}

type systemTracerouteClient struct {
	grpc.ClientStream
}

func (x *systemTracerouteClient) Recv() (*TracerouteResponse, error) {
	m := new(TracerouteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *systemClient) Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error) {
	out := new(TimeResponse)
	err := grpc.Invoke(ctx, "/gnoi.system.System/Time", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SetPackage(ctx context.Context, opts ...grpc.CallOption) (System_SetPackageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_System_serviceDesc.Streams[2], c.cc, "/gnoi.system.System/SetPackage", opts...)
	if err != nil {
		return nil, err
	}
	x := &systemSetPackageClient{stream}
	return x, nil
}

type System_SetPackageClient interface {
	Send(*SetPackageRequest) error
	CloseAndRecv() (*SetPackageResponse, error)
	grpc.ClientStream
}

type systemSetPackageClient struct {
	grpc.ClientStream
}

func (x *systemSetPackageClient) Send(m *SetPackageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *systemSetPackageClient) CloseAndRecv() (*SetPackageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SetPackageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *systemClient) SwitchControlProcessor(ctx context.Context, in *SwitchControlProcessorRequest, opts ...grpc.CallOption) (*SwitchControlProcessorResponse, error) {
	out := new(SwitchControlProcessorResponse)
	err := grpc.Invoke(ctx, "/gnoi.system.System/SwitchControlProcessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error) {
	out := new(RebootResponse)
	err := grpc.Invoke(ctx, "/gnoi.system.System/Reboot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) RebootStatus(ctx context.Context, in *RebootStatusRequest, opts ...grpc.CallOption) (*RebootStatusResponse, error) {
	out := new(RebootStatusResponse)
	err := grpc.Invoke(ctx, "/gnoi.system.System/RebootStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) CancelReboot(ctx context.Context, in *CancelRebootRequest, opts ...grpc.CallOption) (*CancelRebootResponse, error) {
	out := new(CancelRebootResponse)
	err := grpc.Invoke(ctx, "/gnoi.system.System/CancelReboot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for System service

type SystemServer interface {
	// Ping executes the ping command on the target and streams back
	// the results.  Some targets may not stream any results until all
	// results are in.  If a packet count is not explicitly provided,
	// 5 is used.
	Ping(*PingRequest, System_PingServer) error
	// Traceroute executes the traceroute command on the target and streams back
	// the results.  Some targets may not stream any results until all
	// results are in.  If a hop count is not explicitly provided,
	// 30 is used.
	Traceroute(*TracerouteRequest, System_TracerouteServer) error
	// Time returns the current time on the target.  Time is typically used to
	// test if a target is actually responding.
	Time(context.Context, *TimeRequest) (*TimeResponse, error)
	// SetPackage places a software package (possibly including bootable images)
	// on the target. The file is sent in sequential messages, each message
	// up to 64KB of data. A final message must be sent that includes the hash
	// of the data sent. An error is returned if the location does not exist or
	// there is an error writing the data. If no checksum is received, the target
	// must assume the operation is incomplete and remove the partially
	// transmitted file. The target should initially write the file to a temporary location so a failure
	// does not destroy the original file.
	SetPackage(System_SetPackageServer) error
	// SwitchControlProcessor will switch from the current route processor to the
	// provided route processor. If the current route processor is the same as the
	// one provided it is a NOOP. If the target does not exist an error is
	// returned.
	SwitchControlProcessor(context.Context, *SwitchControlProcessorRequest) (*SwitchControlProcessorResponse, error)
	// Reboot causes the target to reboot, possibly at some point in the future.
	// If the method of reboot is not supported then the Reboot RPC will fail.
	// If the reboot is immediate the command will block until the subcomponents
	// have restarted.
	// If a reboot on the active control processor is pending the service must
	// reject all other reboot requests.
	// If a reboot request for active control processor is initiated with other
	// pending reboot requests it must be rejected.
	Reboot(context.Context, *RebootRequest) (*RebootResponse, error)
	// RebootStatus returns the status of reboot for the target.
	RebootStatus(context.Context, *RebootStatusRequest) (*RebootStatusResponse, error)
	// CancelReboot cancels any pending reboot request.
	CancelReboot(context.Context, *CancelRebootRequest) (*CancelRebootResponse, error)
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemServer).Ping(m, &systemPingServer{stream})
}

type System_PingServer interface {
	Send(*PingResponse) error
	grpc.ServerStream
}

type systemPingServer struct {
	grpc.ServerStream
}

func (x *systemPingServer) Send(m *PingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _System_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TracerouteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemServer).Traceroute(m, &systemTracerouteServer{stream})
}

type System_TracerouteServer interface {
	Send(*TracerouteResponse) error
	grpc.ServerStream
}

type systemTracerouteServer struct {
	grpc.ServerStream
}

func (x *systemTracerouteServer) Send(m *TracerouteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _System_Time_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Time(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.system.System/Time",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Time(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SetPackage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SystemServer).SetPackage(&systemSetPackageServer{stream})
}

type System_SetPackageServer interface {
	SendAndClose(*SetPackageResponse) error
	Recv() (*SetPackageRequest, error)
	grpc.ServerStream
}

type systemSetPackageServer struct {
	grpc.ServerStream
}

func (x *systemSetPackageServer) SendAndClose(m *SetPackageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *systemSetPackageServer) Recv() (*SetPackageRequest, error) {
	m := new(SetPackageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _System_SwitchControlProcessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchControlProcessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SwitchControlProcessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.system.System/SwitchControlProcessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SwitchControlProcessor(ctx, req.(*SwitchControlProcessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.system.System/Reboot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_RebootStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).RebootStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.system.System/RebootStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).RebootStatus(ctx, req.(*RebootStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_CancelReboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).CancelReboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.system.System/CancelReboot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).CancelReboot(ctx, req.(*CancelRebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Time",
			Handler:    _System_Time_Handler,
		},
		{
			MethodName: "SwitchControlProcessor",
			Handler:    _System_SwitchControlProcessor_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _System_Reboot_Handler,
		},
		{
			MethodName: "RebootStatus",
			Handler:    _System_RebootStatus_Handler,
		},
		{
			MethodName: "CancelReboot",
			Handler:    _System_CancelReboot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _System_Ping_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _System_Traceroute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetPackage",
			Handler:       _System_SetPackage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/openconfig/gnoi/system/system.proto",
}

func init() { proto.RegisterFile("github.com/openconfig/gnoi/system/system.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xdb, 0xbe,
	0x15, 0xb7, 0xfc, 0xed, 0xe3, 0x24, 0x7f, 0x85, 0xc9, 0x52, 0xd5, 0xdd, 0x5a, 0x4f, 0xe8, 0x8a,
	0xb4, 0x03, 0x9c, 0x2e, 0x2d, 0xd0, 0x61, 0x43, 0x31, 0xb8, 0xb6, 0xd2, 0x04, 0x75, 0x6c, 0x4f,
	0x96, 0x97, 0x01, 0xbb, 0x30, 0x18, 0x99, 0xb1, 0x85, 0xca, 0xa2, 0x26, 0xd2, 0x6e, 0xb3, 0xeb,
	0xdd, 0xed, 0x66, 0x17, 0xc3, 0xb0, 0xdb, 0xbd, 0xc6, 0x5e, 0x64, 0xef, 0xb1, 0x27, 0x18, 0x48,
	0x4a, 0xb6, 0xec, 0xb8, 0x49, 0xf1, 0xbf, 0x32, 0xcf, 0x39, 0xe4, 0xf9, 0xf8, 0x9d, 0x1f, 0xa9,
	0x63, 0x68, 0x4c, 0x3c, 0x3e, 0x9d, 0x5f, 0x37, 0x5c, 0x3a, 0x3b, 0xa1, 0x21, 0x09, 0x5c, 0x1a,
	0xdc, 0x78, 0x93, 0x93, 0x49, 0x40, 0xbd, 0x13, 0x76, 0xcb, 0x38, 0x99, 0xc5, 0x3f, 0x8d, 0x30,
	0xa2, 0x9c, 0xa2, 0xaa, 0xb0, 0x34, 0x94, 0xaa, 0xf6, 0xe2, 0x9e, 0xc3, 0xfc, 0x36, 0x24, 0x4c,
	0x1d, 0x32, 0xff, 0x08, 0x3f, 0x1b, 0x7c, 0xf1, 0xb8, 0x3b, 0x6d, 0xd1, 0x80, 0x47, 0xd4, 0xef,
	0x47, 0xd4, 0x25, 0x8c, 0xd1, 0xc8, 0x26, 0x7f, 0x9e, 0x13, 0xc6, 0xd1, 0x3b, 0xd8, 0x77, 0x95,
	0x69, 0x14, 0x26, 0x36, 0x43, 0xab, 0x6b, 0xc7, 0xd5, 0x53, 0x68, 0xc8, 0x88, 0x7d, 0xcc, 0xa7,
	0xb6, 0xee, 0x6e, 0x9c, 0x37, 0xff, 0xa6, 0xc1, 0xd3, 0x6f, 0xb9, 0x66, 0x21, 0x0d, 0x18, 0xf9,
	0xd1, 0xbe, 0x91, 0x01, 0xa5, 0x05, 0x89, 0x98, 0x47, 0x03, 0x23, 0x5b, 0xd7, 0x8e, 0x2b, 0x76,
	0x22, 0xa2, 0x23, 0x28, 0xce, 0x43, 0xee, 0xcd, 0x88, 0x91, 0xab, 0x6b, 0xc7, 0x39, 0x3b, 0x96,
	0xcc, 0xff, 0x68, 0xb0, 0x6b, 0x93, 0x6b, 0x4a, 0x79, 0x52, 0xd8, 0xaf, 0xa0, 0x38, 0x23, 0x7c,
	0x4a, 0xc7, 0x32, 0xe2, 0xde, 0xe9, 0xe3, 0x46, 0x0a, 0xbf, 0x86, 0xda, 0x7b, 0x29, 0x37, 0xd8,
	0xf1, 0x46, 0x74, 0x08, 0x85, 0x31, 0xf1, 0xf1, 0xad, 0x0c, 0x9a, 0xb7, 0x95, 0x20, 0x92, 0x99,
	0x11, 0xc6, 0xf0, 0x44, 0xc5, 0xac, 0xd8, 0x89, 0x88, 0x5e, 0xc3, 0x2e, 0x9b, 0x5f, 0xbb, 0x74,
	0x16, 0xd2, 0x80, 0x04, 0x9c, 0x19, 0xf9, 0x7a, 0x6e, 0xa3, 0xb6, 0xf5, 0x0d, 0x22, 0xc2, 0x0d,
	0x8d, 0x5c, 0x62, 0x14, 0xea, 0xda, 0x71, 0xd9, 0x56, 0x82, 0xa9, 0xc3, 0x5e, 0x92, 0xbb, 0x42,
	0xce, 0xc4, 0x70, 0xd0, 0xc2, 0x81, 0x4b, 0xfc, 0xf5, 0x9a, 0x52, 0xa9, 0x68, 0x0f, 0xa4, 0x92,
	0x7d, 0x20, 0x15, 0xf3, 0x08, 0x0e, 0xd7, 0x43, 0xc4, 0xa1, 0x3f, 0xc2, 0x81, 0xd2, 0x0c, 0x38,
	0xe6, 0x73, 0x96, 0x84, 0xbe, 0x13, 0x40, 0x7b, 0x28, 0xc0, 0x5f, 0x35, 0x38, 0x5c, 0xf7, 0x14,
	0xd3, 0xe2, 0x08, 0x8a, 0xd8, 0xe5, 0xde, 0x42, 0x15, 0x51, 0xb6, 0x63, 0x09, 0x21, 0xc8, 0x7f,
	0xc1, 0x1e, 0x8f, 0xd1, 0x97, 0x6b, 0xa9, 0x9b, 0x92, 0x40, 0x22, 0x2f, 0x74, 0x53, 0x22, 0x39,
	0x10, 0x11, 0xcc, 0x68, 0x60, 0xe4, 0x25, 0x08, 0xb1, 0x24, 0xc0, 0x75, 0xe9, 0x3c, 0xe0, 0x12,
	0xdc, 0x5d, 0x5b, 0x09, 0xe6, 0x2e, 0x54, 0x1d, 0x6f, 0x46, 0xe2, 0x3a, 0x4c, 0x13, 0x76, 0x94,
	0x18, 0x27, 0x83, 0x20, 0x2f, 0xe9, 0xa4, 0xa9, 0x00, 0x92, 0x4c, 0xff, 0xce, 0x42, 0xb5, 0xef,
	0x05, 0x93, 0xa4, 0xf6, 0x3a, 0x54, 0xc7, 0x84, 0x71, 0x2f, 0xc0, 0x5c, 0x50, 0x52, 0x41, 0x9f,
	0x56, 0x89, 0x94, 0x18, 0x9d, 0x8b, 0xc6, 0x2a, 0xbe, 0xc6, 0xd2, 0x2a, 0x25, 0x91, 0x7f, 0x21,
	0x4e, 0x09, 0xd5, 0xa0, 0xec, 0x05, 0x9c, 0x44, 0x0b, 0xec, 0xcb, 0x12, 0x72, 0xf6, 0x52, 0x5e,
	0x82, 0x50, 0x90, 0xfa, 0x25, 0x08, 0xcc, 0xfb, 0x0b, 0x31, 0x8a, 0xd2, 0x89, 0x5c, 0xa3, 0x17,
	0xf0, 0xc3, 0x98, 0x8e, 0x02, 0xca, 0x47, 0x37, 0x11, 0x9e, 0xcc, 0x48, 0xc0, 0x8d, 0x92, 0x44,
	0x73, 0x77, 0x4c, 0xbb, 0x94, 0x9f, 0xc5, 0x4a, 0xf4, 0x1c, 0xf6, 0xe2, 0x7d, 0x11, 0x61, 0xd4,
	0x5f, 0x10, 0xa3, 0x2c, 0xb7, 0xed, 0xc8, 0x6d, 0xb6, 0xd2, 0xa1, 0xd7, 0x00, 0xfe, 0x1b, 0xf9,
	0x62, 0xb8, 0xd4, 0x37, 0x2a, 0xf2, 0xc2, 0xe8, 0xaa, 0xb5, 0x9d, 0x37, 0xfd, 0x58, 0x6f, 0xa7,
	0xf6, 0x98, 0xff, 0xca, 0xc2, 0x8e, 0xc2, 0x68, 0xd5, 0xd5, 0x18, 0x02, 0x6d, 0x0d, 0x82, 0x04,
	0xe0, 0xac, 0x2a, 0x48, 0xac, 0x65, 0x41, 0x64, 0x89, 0x8a, 0x5c, 0x0b, 0x50, 0x22, 0xe2, 0x12,
	0x6f, 0x41, 0xc6, 0x12, 0x94, 0x82, 0xbd, 0x94, 0xd1, 0x63, 0x28, 0xcf, 0xbc, 0x60, 0x24, 0xfd,
	0x28, 0x60, 0x4a, 0x33, 0x2f, 0x10, 0x7d, 0x14, 0x26, 0xbc, 0x98, 0x28, 0x53, 0x51, 0x99, 0xf0,
	0x62, 0x92, 0x98, 0x66, 0xf8, 0xab, 0x32, 0x95, 0xe2, 0x53, 0xf8, 0xab, 0x34, 0x3d, 0x82, 0x12,
	0xe3, 0xe3, 0xd1, 0x98, 0x2c, 0x24, 0x1c, 0x39, 0xbb, 0xc8, 0xf8, 0xb8, 0x4d, 0x16, 0xa2, 0x61,
	0xd7, 0xb7, 0x9c, 0x30, 0xa3, 0xaa, 0x1a, 0x26, 0x05, 0x91, 0x1b, 0x13, 0x5c, 0x08, 0x5c, 0x62,
	0xec, 0xa8, 0xdc, 0x12, 0x19, 0xe9, 0x90, 0xe3, 0xdc, 0x37, 0x76, 0xa5, 0x5a, 0x2c, 0xcd, 0xbf,
	0xe7, 0x60, 0xdf, 0x89, 0xb0, 0x4b, 0x22, 0x3a, 0xe7, 0x09, 0xf1, 0xbe, 0x89, 0xcf, 0x06, 0xb9,
	0xb2, 0x77, 0xc9, 0xf5, 0x0c, 0xaa, 0x5e, 0xe0, 0x71, 0x0f, 0xfb, 0x23, 0x11, 0x29, 0x27, 0xd9,
	0x0d, 0xb1, 0xca, 0xe1, 0xbe, 0xa8, 0x46, 0x16, 0xca, 0xfd, 0x18, 0xb9, 0xa2, 0xa8, 0x93, 0x6f,
	0x27, 0xd3, 0x16, 0xe2, 0x14, 0xbf, 0x8f, 0x38, 0xa5, 0x07, 0x89, 0x53, 0x7e, 0x98, 0x38, 0xe8,
	0x02, 0xc0, 0x7f, 0xbb, 0x41, 0xb5, 0x97, 0x6b, 0x6f, 0xf3, 0x1d, 0xec, 0x1a, 0x9d, 0xb7, 0x29,
	0x57, 0xcb, 0xc3, 0xe6, 0x31, 0xc0, 0xca, 0x82, 0xca, 0x90, 0xbf, 0x68, 0x5d, 0xf6, 0xf5, 0x0c,
	0x2a, 0x41, 0xce, 0x69, 0xf5, 0x75, 0x4d, 0x2c, 0x86, 0xed, 0xbe, 0x9e, 0x35, 0xff, 0x5b, 0x00,
	0x94, 0x76, 0x1b, 0x73, 0xf6, 0x25, 0xe8, 0x29, 0xa0, 0x47, 0x01, 0x9e, 0x25, 0xdd, 0xf9, 0x21,
	0xa5, 0xef, 0xe2, 0x19, 0x41, 0x27, 0x70, 0x90, 0xde, 0x8a, 0xc7, 0xe3, 0x88, 0x30, 0x16, 0xb7,
	0x0b, 0xa5, 0x4c, 0x4d, 0x65, 0x11, 0xd8, 0x4f, 0x69, 0xc8, 0x12, 0x8e, 0x8b, 0xb5, 0xe8, 0x64,
	0x88, 0xdd, 0xcf, 0x84, 0x8f, 0xe4, 0x7d, 0x56, 0xcd, 0x02, 0xa5, 0x1a, 0x88, 0x5b, 0xad, 0x43,
	0x6e, 0x4a, 0x43, 0xd9, 0xaf, 0x82, 0x2d, 0x96, 0xe2, 0xc9, 0x4f, 0x62, 0x15, 0xd5, 0x93, 0x8f,
	0x57, 0x01, 0x64, 0xc2, 0x25, 0xa9, 0x96, 0x6b, 0x71, 0x3e, 0xe2, 0x3c, 0xe6, 0xb4, 0x58, 0xa2,
	0xdf, 0x42, 0x81, 0x71, 0xcc, 0x49, 0x8c, 0xf4, 0x2f, 0xbe, 0x89, 0xb4, 0x82, 0xa4, 0x21, 0xde,
	0x6a, 0x62, 0xab, 0x33, 0xe8, 0x09, 0x54, 0x3c, 0x77, 0x16, 0x8e, 0x5c, 0x3a, 0x26, 0x06, 0x28,
	0xe2, 0x0b, 0x45, 0x8b, 0x8e, 0x09, 0x7a, 0x0f, 0xf9, 0x59, 0xe8, 0x8b, 0x9b, 0x22, 0x3e, 0x04,
	0x2f, 0x1f, 0x72, 0x7c, 0x19, 0xfa, 0xcc, 0x0a, 0x78, 0x74, 0x6b, 0xcb, 0x63, 0x82, 0xb4, 0x98,
	0x8d, 0x42, 0xcc, 0xa7, 0xc6, 0x4e, 0x3d, 0x27, 0x48, 0x8b, 0x99, 0xf8, 0x8c, 0xd4, 0xde, 0x41,
	0x65, 0xb9, 0x57, 0x14, 0xf4, 0x99, 0xdc, 0xc6, 0x4d, 0x11, 0x4b, 0x71, 0x43, 0x17, 0xd8, 0x9f,
	0x27, 0x2f, 0xad, 0x12, 0x7e, 0x93, 0xfd, 0xb5, 0x66, 0xfe, 0x4f, 0x83, 0x82, 0x4c, 0x1f, 0x55,
	0xa1, 0xd4, 0xb6, 0xce, 0x9a, 0xc3, 0x8e, 0xa3, 0x67, 0x04, 0x2f, 0xba, 0xbd, 0xae, 0xa5, 0x6b,
	0x42, 0x3d, 0xec, 0x7e, 0xea, 0xf6, 0xae, 0xba, 0x7a, 0x76, 0x49, 0x97, 0x1c, 0x3a, 0x04, 0xfd,
	0xbc, 0x37, 0x70, 0x46, 0xc3, 0xae, 0x6d, 0x35, 0x5b, 0xe7, 0xcd, 0x0f, 0x1d, 0x4b, 0xcf, 0xa3,
	0x47, 0x70, 0xd0, 0xb5, 0x9c, 0xab, 0x9e, 0xfd, 0x69, 0xcd, 0x50, 0x40, 0x06, 0x1c, 0xf6, 0xed,
	0x9e, 0xd3, 0x6b, 0xf5, 0x3a, 0x6b, 0x96, 0xa2, 0x38, 0x32, 0xe8, 0x0d, 0xed, 0x96, 0x35, 0xb2,
	0x7b, 0x43, 0xc7, 0x1a, 0x9d, 0x35, 0x2f, 0x3a, 0x56, 0x5b, 0x2f, 0x89, 0x23, 0x67, 0x76, 0xf3,
	0xe3, 0xa5, 0xd5, 0x75, 0x9a, 0xce, 0x45, 0xaf, 0x3b, 0xea, 0x5a, 0x56, 0xdb, 0x6a, 0xeb, 0x65,
	0xb4, 0x07, 0xd0, 0xb7, 0x7b, 0xe7, 0x17, 0x1f, 0x2e, 0x1c, 0xab, 0xad, 0x57, 0x94, 0x73, 0xab,
	0x65, 0xb5, 0xad, 0x6e, 0xcb, 0x1a, 0xfd, 0xe1, 0xa2, 0xd7, 0x91, 0x07, 0x74, 0x40, 0x3f, 0x81,
	0xfd, 0x94, 0xa5, 0x35, 0x74, 0x7a, 0x67, 0x67, 0x7a, 0xd5, 0xfc, 0x13, 0x94, 0xfa, 0xd8, 0xfd,
	0x2c, 0x66, 0x80, 0x1a, 0x94, 0x6f, 0x3c, 0x9f, 0xa4, 0x58, 0xbc, 0x94, 0xd3, 0x13, 0x55, 0x7e,
	0x7d, 0xa2, 0xaa, 0x41, 0x59, 0x7e, 0x7f, 0x05, 0x47, 0xd4, 0x54, 0xb2, 0x94, 0xcd, 0x7f, 0x68,
	0xb0, 0x3f, 0x20, 0x3c, 0x0e, 0xb0, 0x1a, 0x05, 0x4a, 0xa1, 0xd2, 0xc4, 0xc3, 0xdc, 0xe1, 0x5a,
	0xef, 0xe3, 0xdd, 0xe7, 0x19, 0x3b, 0xd9, 0x86, 0x7e, 0x0a, 0x65, 0x31, 0xe3, 0xc5, 0x83, 0x89,
	0x76, 0xbc, 0x73, 0x9e, 0xb1, 0x97, 0x1a, 0xf4, 0x1c, 0xf2, 0x53, 0xcc, 0xa6, 0xf2, 0xa6, 0x54,
	0x4f, 0xf7, 0x94, 0xb3, 0x73, 0xcc, 0xa6, 0xce, 0x6d, 0x28, 0xdc, 0x48, 0xeb, 0x87, 0x0a, 0x94,
	0xa2, 0xf8, 0x1b, 0x7e, 0x08, 0x28, 0x9d, 0x95, 0x22, 0xd8, 0x2b, 0x0f, 0x76, 0xd2, 0x53, 0x5d,
	0xba, 0xdb, 0x92, 0x04, 0xad, 0x5e, 0xa7, 0xad, 0x6b, 0x68, 0x17, 0x2a, 0xfd, 0xde, 0x95, 0x65,
	0xb7, 0x97, 0x34, 0x38, 0x6f, 0x76, 0x1c, 0x3d, 0x27, 0x56, 0x57, 0x4d, 0xfb, 0x52, 0xcf, 0x8b,
	0x67, 0xa3, 0x3b, 0x38, 0xd3, 0x0b, 0xa8, 0x02, 0x05, 0xdb, 0x1a, 0x58, 0x8e, 0x5e, 0x14, 0xde,
	0xe4, 0xb1, 0x61, 0x5f, 0x2f, 0x9d, 0xfe, 0xb3, 0x00, 0xc5, 0x81, 0xac, 0x16, 0xfd, 0x0e, 0xf2,
	0xe2, 0x33, 0x88, 0x8c, 0x75, 0x0c, 0x56, 0xd3, 0x43, 0xed, 0xf1, 0x16, 0x4b, 0x3c, 0x6b, 0x65,
	0x5e, 0x6b, 0xe8, 0xf7, 0x00, 0xab, 0xdb, 0x82, 0x9e, 0xde, 0xff, 0x12, 0xd6, 0x9e, 0x3d, 0x70,
	0xcd, 0xa4, 0xcb, 0xf7, 0x90, 0x97, 0x5f, 0xb9, 0xf5, 0x9c, 0x52, 0x53, 0xd0, 0x46, 0x4e, 0xe9,
	0x81, 0xc8, 0xcc, 0x88, 0x8c, 0x56, 0xf0, 0x6e, 0x64, 0x74, 0x87, 0x0d, 0x1b, 0x19, 0xdd, 0xed,
	0x8b, 0x99, 0x39, 0xd6, 0x10, 0x83, 0xa3, 0xed, 0xff, 0x15, 0xd0, 0xab, 0xf5, 0xe3, 0xf7, 0xfd,
	0x57, 0xa9, 0xfd, 0xf2, 0xbb, 0xf6, 0x2e, 0xeb, 0x68, 0x41, 0x51, 0x11, 0x02, 0xd5, 0xb6, 0xcc,
	0xfe, 0x89, 0xd3, 0x27, 0x5b, 0x6d, 0x4b, 0x27, 0xc3, 0x84, 0x55, 0x6a, 0x88, 0x45, 0xf5, 0x2d,
	0xdb, 0xd7, 0x26, 0xe5, 0xda, 0xcf, 0xef, 0xd9, 0x91, 0x76, 0x9b, 0x9e, 0xbe, 0x37, 0xdc, 0x6e,
	0x99, 0xfd, 0x37, 0xdc, 0x6e, 0x1d, 0xdd, 0x33, 0xd7, 0x45, 0xf9, 0x6d, 0x7c, 0xf3, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf5, 0xc0, 0x29, 0xeb, 0x5c, 0x0e, 0x00, 0x00,
}
