// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/openconfig/gnoi/factory_reset/factory_reset.proto

package factory_reset

import (
	_ "github.com/openconfig/gnoi/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactoryOs     bool                   `protobuf:"varint,1,opt,name=factory_os,json=factoryOs,proto3" json:"factory_os,omitempty"`
	ZeroFill      bool                   `protobuf:"varint,2,opt,name=zero_fill,json=zeroFill,proto3" json:"zero_fill,omitempty"`
	RetainCerts   bool                   `protobuf:"varint,3,opt,name=retain_certs,json=retainCerts,proto3" json:"retain_certs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetFactoryOs() bool {
	if x != nil {
		return x.FactoryOs
	}
	return false
}

func (x *StartRequest) GetZeroFill() bool {
	if x != nil {
		return x.ZeroFill
	}
	return false
}

func (x *StartRequest) GetRetainCerts() bool {
	if x != nil {
		return x.RetainCerts
	}
	return false
}

type ResetSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSuccess) Reset() {
	*x = ResetSuccess{}
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSuccess) ProtoMessage() {}

func (x *ResetSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSuccess.ProtoReflect.Descriptor instead.
func (*ResetSuccess) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescGZIP(), []int{1}
}

type ResetError struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FactoryOsUnsupported bool                   `protobuf:"varint,1,opt,name=factory_os_unsupported,json=factoryOsUnsupported,proto3" json:"factory_os_unsupported,omitempty"`
	ZeroFillUnsupported  bool                   `protobuf:"varint,2,opt,name=zero_fill_unsupported,json=zeroFillUnsupported,proto3" json:"zero_fill_unsupported,omitempty"`
	Other                bool                   `protobuf:"varint,3,opt,name=other,proto3" json:"other,omitempty"`
	Detail               string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResetError) Reset() {
	*x = ResetError{}
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetError) ProtoMessage() {}

func (x *ResetError) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetError.ProtoReflect.Descriptor instead.
func (*ResetError) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescGZIP(), []int{2}
}

func (x *ResetError) GetFactoryOsUnsupported() bool {
	if x != nil {
		return x.FactoryOsUnsupported
	}
	return false
}

func (x *ResetError) GetZeroFillUnsupported() bool {
	if x != nil {
		return x.ZeroFillUnsupported
	}
	return false
}

func (x *ResetError) GetOther() bool {
	if x != nil {
		return x.Other
	}
	return false
}

func (x *ResetError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StartResponse_ResetSuccess
	//	*StartResponse_ResetError
	Response      isStartResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetResponse() isStartResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StartResponse) GetResetSuccess() *ResetSuccess {
	if x != nil {
		if x, ok := x.Response.(*StartResponse_ResetSuccess); ok {
			return x.ResetSuccess
		}
	}
	return nil
}

func (x *StartResponse) GetResetError() *ResetError {
	if x != nil {
		if x, ok := x.Response.(*StartResponse_ResetError); ok {
			return x.ResetError
		}
	}
	return nil
}

type isStartResponse_Response interface {
	isStartResponse_Response()
}

type StartResponse_ResetSuccess struct {
	ResetSuccess *ResetSuccess `protobuf:"bytes,1,opt,name=reset_success,json=resetSuccess,proto3,oneof"`
}

type StartResponse_ResetError struct {
	ResetError *ResetError `protobuf:"bytes,2,opt,name=reset_error,json=resetError,proto3,oneof"`
}

func (*StartResponse_ResetSuccess) isStartResponse_Response() {}

func (*StartResponse_ResetError) isStartResponse_Response() {}

var File_github_com_openconfig_gnoi_factory_reset_factory_reset_proto protoreflect.FileDescriptor

const file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDesc = "" +
	"\n" +
	"<github.com/openconfig/gnoi/factory_reset/factory_reset.proto\x12\x12gnoi.factory_reset\x1a,github.com/openconfig/gnoi/types/types.proto\"m\n" +
	"\fStartRequest\x12\x1d\n" +
	"\n" +
	"factory_os\x18\x01 \x01(\bR\tfactoryOs\x12\x1b\n" +
	"\tzero_fill\x18\x02 \x01(\bR\bzeroFill\x12!\n" +
	"\fretain_certs\x18\x03 \x01(\bR\vretainCerts\"\x0e\n" +
	"\fResetSuccess\"\xa4\x01\n" +
	"\n" +
	"ResetError\x124\n" +
	"\x16factory_os_unsupported\x18\x01 \x01(\bR\x14factoryOsUnsupported\x122\n" +
	"\x15zero_fill_unsupported\x18\x02 \x01(\bR\x13zeroFillUnsupported\x12\x14\n" +
	"\x05other\x18\x03 \x01(\bR\x05other\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xa7\x01\n" +
	"\rStartResponse\x12G\n" +
	"\rreset_success\x18\x01 \x01(\v2 .gnoi.factory_reset.ResetSuccessH\x00R\fresetSuccess\x12A\n" +
	"\vreset_error\x18\x02 \x01(\v2\x1e.gnoi.factory_reset.ResetErrorH\x00R\n" +
	"resetErrorB\n" +
	"\n" +
	"\bresponse2\\\n" +
	"\fFactoryReset\x12L\n" +
	"\x05Start\x12 .gnoi.factory_reset.StartRequest\x1a!.gnoi.factory_reset.StartResponseB2\xd2>\x050.1.0Z(github.com/openconfig/gnoi/factory_resetb\x06proto3"

var (
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescOnce sync.Once
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescData []byte
)

func file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDesc), len(file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDesc)))
	})
	return file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDescData
}

var file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_goTypes = []any{
	(*StartRequest)(nil),  // 0: gnoi.factory_reset.StartRequest
	(*ResetSuccess)(nil),  // 1: gnoi.factory_reset.ResetSuccess
	(*ResetError)(nil),    // 2: gnoi.factory_reset.ResetError
	(*StartResponse)(nil), // 3: gnoi.factory_reset.StartResponse
}
var file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_depIdxs = []int32{
	1, // 0: gnoi.factory_reset.StartResponse.reset_success:type_name -> gnoi.factory_reset.ResetSuccess
	2, // 1: gnoi.factory_reset.StartResponse.reset_error:type_name -> gnoi.factory_reset.ResetError
	0, // 2: gnoi.factory_reset.FactoryReset.Start:input_type -> gnoi.factory_reset.StartRequest
	3, // 3: gnoi.factory_reset.FactoryReset.Start:output_type -> gnoi.factory_reset.StartResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_init() }
func file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_init() {
	if File_github_com_openconfig_gnoi_factory_reset_factory_reset_proto != nil {
		return
	}
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes[3].OneofWrappers = []any{
		(*StartResponse_ResetSuccess)(nil),
		(*StartResponse_ResetError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDesc), len(file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_depIdxs,
		MessageInfos:      file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_gnoi_factory_reset_factory_reset_proto = out.File
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_goTypes = nil
	file_github_com_openconfig_gnoi_factory_reset_factory_reset_proto_depIdxs = nil
}
