// Code generated by protoc-gen-go. DO NOT EDIT.
// source: layer2/layer2.proto

package gnoi_layer2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	types "github.com/openconfig/gnoi/types"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PerformBERTResponse_BERTState int32

const (
	PerformBERTResponse_UNKNOWN  PerformBERTResponse_BERTState = 0
	PerformBERTResponse_DISABLED PerformBERTResponse_BERTState = 1
	PerformBERTResponse_RUNNING  PerformBERTResponse_BERTState = 2
	PerformBERTResponse_COMPLETE PerformBERTResponse_BERTState = 3
	PerformBERTResponse_ERROR    PerformBERTResponse_BERTState = 4
)

var PerformBERTResponse_BERTState_name = map[int32]string{
	0: "UNKNOWN",
	1: "DISABLED",
	2: "RUNNING",
	3: "COMPLETE",
	4: "ERROR",
}

var PerformBERTResponse_BERTState_value = map[string]int32{
	"UNKNOWN":  0,
	"DISABLED": 1,
	"RUNNING":  2,
	"COMPLETE": 3,
	"ERROR":    4,
}

func (x PerformBERTResponse_BERTState) String() string {
	return proto.EnumName(PerformBERTResponse_BERTState_name, int32(x))
}

func (PerformBERTResponse_BERTState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{5, 0}
}

type ClearNeighborDiscoveryRequest struct {
	Protocol             types.L3Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=types.L3Protocol" json:"protocol,omitempty"`
	Address              string           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClearNeighborDiscoveryRequest) Reset()         { *m = ClearNeighborDiscoveryRequest{} }
func (m *ClearNeighborDiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*ClearNeighborDiscoveryRequest) ProtoMessage()    {}
func (*ClearNeighborDiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{0}
}

func (m *ClearNeighborDiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearNeighborDiscoveryRequest.Unmarshal(m, b)
}
func (m *ClearNeighborDiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearNeighborDiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *ClearNeighborDiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearNeighborDiscoveryRequest.Merge(m, src)
}
func (m *ClearNeighborDiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_ClearNeighborDiscoveryRequest.Size(m)
}
func (m *ClearNeighborDiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearNeighborDiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearNeighborDiscoveryRequest proto.InternalMessageInfo

func (m *ClearNeighborDiscoveryRequest) GetProtocol() types.L3Protocol {
	if m != nil {
		return m.Protocol
	}
	return types.L3Protocol_UNSPECIFIED
}

func (m *ClearNeighborDiscoveryRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClearNeighborDiscoveryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearNeighborDiscoveryResponse) Reset()         { *m = ClearNeighborDiscoveryResponse{} }
func (m *ClearNeighborDiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*ClearNeighborDiscoveryResponse) ProtoMessage()    {}
func (*ClearNeighborDiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{1}
}

func (m *ClearNeighborDiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearNeighborDiscoveryResponse.Unmarshal(m, b)
}
func (m *ClearNeighborDiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearNeighborDiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *ClearNeighborDiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearNeighborDiscoveryResponse.Merge(m, src)
}
func (m *ClearNeighborDiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_ClearNeighborDiscoveryResponse.Size(m)
}
func (m *ClearNeighborDiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearNeighborDiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearNeighborDiscoveryResponse proto.InternalMessageInfo

type ClearSpanningTreeRequest struct {
	Interface            *types.Path `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClearSpanningTreeRequest) Reset()         { *m = ClearSpanningTreeRequest{} }
func (m *ClearSpanningTreeRequest) String() string { return proto.CompactTextString(m) }
func (*ClearSpanningTreeRequest) ProtoMessage()    {}
func (*ClearSpanningTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{2}
}

func (m *ClearSpanningTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearSpanningTreeRequest.Unmarshal(m, b)
}
func (m *ClearSpanningTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearSpanningTreeRequest.Marshal(b, m, deterministic)
}
func (m *ClearSpanningTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearSpanningTreeRequest.Merge(m, src)
}
func (m *ClearSpanningTreeRequest) XXX_Size() int {
	return xxx_messageInfo_ClearSpanningTreeRequest.Size(m)
}
func (m *ClearSpanningTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearSpanningTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearSpanningTreeRequest proto.InternalMessageInfo

func (m *ClearSpanningTreeRequest) GetInterface() *types.Path {
	if m != nil {
		return m.Interface
	}
	return nil
}

type ClearSpanningTreeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearSpanningTreeResponse) Reset()         { *m = ClearSpanningTreeResponse{} }
func (m *ClearSpanningTreeResponse) String() string { return proto.CompactTextString(m) }
func (*ClearSpanningTreeResponse) ProtoMessage()    {}
func (*ClearSpanningTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{3}
}

func (m *ClearSpanningTreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearSpanningTreeResponse.Unmarshal(m, b)
}
func (m *ClearSpanningTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearSpanningTreeResponse.Marshal(b, m, deterministic)
}
func (m *ClearSpanningTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearSpanningTreeResponse.Merge(m, src)
}
func (m *ClearSpanningTreeResponse) XXX_Size() int {
	return xxx_messageInfo_ClearSpanningTreeResponse.Size(m)
}
func (m *ClearSpanningTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearSpanningTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearSpanningTreeResponse proto.InternalMessageInfo

type PerformBERTRequest struct {
	// ID for retrieving a previous BERT run data - optional.
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interface            *types.Path `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PerformBERTRequest) Reset()         { *m = PerformBERTRequest{} }
func (m *PerformBERTRequest) String() string { return proto.CompactTextString(m) }
func (*PerformBERTRequest) ProtoMessage()    {}
func (*PerformBERTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{4}
}

func (m *PerformBERTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerformBERTRequest.Unmarshal(m, b)
}
func (m *PerformBERTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerformBERTRequest.Marshal(b, m, deterministic)
}
func (m *PerformBERTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerformBERTRequest.Merge(m, src)
}
func (m *PerformBERTRequest) XXX_Size() int {
	return xxx_messageInfo_PerformBERTRequest.Size(m)
}
func (m *PerformBERTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PerformBERTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PerformBERTRequest proto.InternalMessageInfo

func (m *PerformBERTRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PerformBERTRequest) GetInterface() *types.Path {
	if m != nil {
		return m.Interface
	}
	return nil
}

type PerformBERTResponse struct {
	Id                   string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                PerformBERTResponse_BERTState `protobuf:"varint,2,opt,name=state,proto3,enum=gnoi.layer2.PerformBERTResponse_BERTState" json:"state,omitempty"`
	ElapsedPeriod        int64                         `protobuf:"varint,3,opt,name=elapsed_period,json=elapsedPeriod,proto3" json:"elapsed_period,omitempty"`
	Pattern              []byte                        `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Errors               int64                         `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`
	ReceivedBits         int64                         `protobuf:"varint,6,opt,name=received_bits,json=receivedBits,proto3" json:"received_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PerformBERTResponse) Reset()         { *m = PerformBERTResponse{} }
func (m *PerformBERTResponse) String() string { return proto.CompactTextString(m) }
func (*PerformBERTResponse) ProtoMessage()    {}
func (*PerformBERTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{5}
}

func (m *PerformBERTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerformBERTResponse.Unmarshal(m, b)
}
func (m *PerformBERTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerformBERTResponse.Marshal(b, m, deterministic)
}
func (m *PerformBERTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerformBERTResponse.Merge(m, src)
}
func (m *PerformBERTResponse) XXX_Size() int {
	return xxx_messageInfo_PerformBERTResponse.Size(m)
}
func (m *PerformBERTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PerformBERTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PerformBERTResponse proto.InternalMessageInfo

func (m *PerformBERTResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PerformBERTResponse) GetState() PerformBERTResponse_BERTState {
	if m != nil {
		return m.State
	}
	return PerformBERTResponse_UNKNOWN
}

func (m *PerformBERTResponse) GetElapsedPeriod() int64 {
	if m != nil {
		return m.ElapsedPeriod
	}
	return 0
}

func (m *PerformBERTResponse) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *PerformBERTResponse) GetErrors() int64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *PerformBERTResponse) GetReceivedBits() int64 {
	if m != nil {
		return m.ReceivedBits
	}
	return 0
}

type ClearLLDPInterfaceRequest struct {
	Interface            *types.Path `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClearLLDPInterfaceRequest) Reset()         { *m = ClearLLDPInterfaceRequest{} }
func (m *ClearLLDPInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*ClearLLDPInterfaceRequest) ProtoMessage()    {}
func (*ClearLLDPInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{6}
}

func (m *ClearLLDPInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearLLDPInterfaceRequest.Unmarshal(m, b)
}
func (m *ClearLLDPInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearLLDPInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *ClearLLDPInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearLLDPInterfaceRequest.Merge(m, src)
}
func (m *ClearLLDPInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_ClearLLDPInterfaceRequest.Size(m)
}
func (m *ClearLLDPInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearLLDPInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearLLDPInterfaceRequest proto.InternalMessageInfo

func (m *ClearLLDPInterfaceRequest) GetInterface() *types.Path {
	if m != nil {
		return m.Interface
	}
	return nil
}

type ClearLLDPInterfaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearLLDPInterfaceResponse) Reset()         { *m = ClearLLDPInterfaceResponse{} }
func (m *ClearLLDPInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*ClearLLDPInterfaceResponse) ProtoMessage()    {}
func (*ClearLLDPInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{7}
}

func (m *ClearLLDPInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearLLDPInterfaceResponse.Unmarshal(m, b)
}
func (m *ClearLLDPInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearLLDPInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *ClearLLDPInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearLLDPInterfaceResponse.Merge(m, src)
}
func (m *ClearLLDPInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_ClearLLDPInterfaceResponse.Size(m)
}
func (m *ClearLLDPInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearLLDPInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearLLDPInterfaceResponse proto.InternalMessageInfo

type SendWakeOnLANRequest struct {
	Interface            *types.Path `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Address              string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MacAddress           []byte      `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendWakeOnLANRequest) Reset()         { *m = SendWakeOnLANRequest{} }
func (m *SendWakeOnLANRequest) String() string { return proto.CompactTextString(m) }
func (*SendWakeOnLANRequest) ProtoMessage()    {}
func (*SendWakeOnLANRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{8}
}

func (m *SendWakeOnLANRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWakeOnLANRequest.Unmarshal(m, b)
}
func (m *SendWakeOnLANRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWakeOnLANRequest.Marshal(b, m, deterministic)
}
func (m *SendWakeOnLANRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWakeOnLANRequest.Merge(m, src)
}
func (m *SendWakeOnLANRequest) XXX_Size() int {
	return xxx_messageInfo_SendWakeOnLANRequest.Size(m)
}
func (m *SendWakeOnLANRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWakeOnLANRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendWakeOnLANRequest proto.InternalMessageInfo

func (m *SendWakeOnLANRequest) GetInterface() *types.Path {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *SendWakeOnLANRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendWakeOnLANRequest) GetMacAddress() []byte {
	if m != nil {
		return m.MacAddress
	}
	return nil
}

type SendWakeOnLANResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWakeOnLANResponse) Reset()         { *m = SendWakeOnLANResponse{} }
func (m *SendWakeOnLANResponse) String() string { return proto.CompactTextString(m) }
func (*SendWakeOnLANResponse) ProtoMessage()    {}
func (*SendWakeOnLANResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff9ec617d9e4348, []int{9}
}

func (m *SendWakeOnLANResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWakeOnLANResponse.Unmarshal(m, b)
}
func (m *SendWakeOnLANResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWakeOnLANResponse.Marshal(b, m, deterministic)
}
func (m *SendWakeOnLANResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWakeOnLANResponse.Merge(m, src)
}
func (m *SendWakeOnLANResponse) XXX_Size() int {
	return xxx_messageInfo_SendWakeOnLANResponse.Size(m)
}
func (m *SendWakeOnLANResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWakeOnLANResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendWakeOnLANResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("gnoi.layer2.PerformBERTResponse_BERTState", PerformBERTResponse_BERTState_name, PerformBERTResponse_BERTState_value)
	proto.RegisterType((*ClearNeighborDiscoveryRequest)(nil), "gnoi.layer2.ClearNeighborDiscoveryRequest")
	proto.RegisterType((*ClearNeighborDiscoveryResponse)(nil), "gnoi.layer2.ClearNeighborDiscoveryResponse")
	proto.RegisterType((*ClearSpanningTreeRequest)(nil), "gnoi.layer2.ClearSpanningTreeRequest")
	proto.RegisterType((*ClearSpanningTreeResponse)(nil), "gnoi.layer2.ClearSpanningTreeResponse")
	proto.RegisterType((*PerformBERTRequest)(nil), "gnoi.layer2.PerformBERTRequest")
	proto.RegisterType((*PerformBERTResponse)(nil), "gnoi.layer2.PerformBERTResponse")
	proto.RegisterType((*ClearLLDPInterfaceRequest)(nil), "gnoi.layer2.ClearLLDPInterfaceRequest")
	proto.RegisterType((*ClearLLDPInterfaceResponse)(nil), "gnoi.layer2.ClearLLDPInterfaceResponse")
	proto.RegisterType((*SendWakeOnLANRequest)(nil), "gnoi.layer2.SendWakeOnLANRequest")
	proto.RegisterType((*SendWakeOnLANResponse)(nil), "gnoi.layer2.SendWakeOnLANResponse")
}

func init() { proto.RegisterFile("layer2/layer2.proto", fileDescriptor_dff9ec617d9e4348) }

var fileDescriptor_dff9ec617d9e4348 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0x8d, 0x21, 0x90, 0x30, 0x24, 0x88, 0x6c, 0xbe, 0x2f, 0x75, 0xe9, 0x4f, 0xa8, 0xab, 0xb4,
	0xf4, 0xcf, 0xa4, 0xe4, 0xbe, 0x6a, 0x08, 0xb4, 0x8a, 0xea, 0x1a, 0xb4, 0x10, 0xa5, 0x77, 0x91,
	0xb1, 0x27, 0xb0, 0x2a, 0x78, 0xdd, 0xdd, 0x4d, 0xa4, 0x48, 0x7d, 0xab, 0xbe, 0x49, 0x9f, 0xa7,
	0x17, 0x15, 0xfe, 0xa1, 0xa1, 0x38, 0xa1, 0xed, 0x0d, 0x68, 0x66, 0xce, 0x9c, 0x33, 0xda, 0x33,
	0x63, 0xd8, 0x1e, 0x3b, 0x57, 0x28, 0x1a, 0xf5, 0xe8, 0xcf, 0x0c, 0x04, 0x57, 0x9c, 0x14, 0x87,
	0x3e, 0x67, 0x66, 0x94, 0xaa, 0xbc, 0x1c, 0x32, 0x35, 0xba, 0x18, 0x98, 0x2e, 0x9f, 0xd4, 0x79,
	0x80, 0xbe, 0xcb, 0xfd, 0x73, 0x36, 0xac, 0x4f, 0x21, 0x75, 0x75, 0x15, 0xa0, 0x8c, 0x7e, 0xa3,
	0x56, 0x63, 0x04, 0x0f, 0x8e, 0xc6, 0xe8, 0x08, 0x1b, 0xd9, 0x70, 0x34, 0xe0, 0xa2, 0xc5, 0xa4,
	0xcb, 0x2f, 0x51, 0x5c, 0x51, 0xfc, 0x72, 0x81, 0x52, 0x91, 0x57, 0xb0, 0x1e, 0x22, 0x5d, 0x3e,
	0xd6, 0xb5, 0xaa, 0x56, 0x2b, 0x35, 0xb6, 0xcc, 0x88, 0xc0, 0x3a, 0xe8, 0xc6, 0x05, 0x3a, 0x83,
	0x10, 0x1d, 0xd6, 0x1c, 0xcf, 0x13, 0x28, 0xa5, 0x9e, 0xa9, 0x6a, 0xb5, 0x02, 0x4d, 0x42, 0xa3,
	0x0a, 0x0f, 0x6f, 0x52, 0x92, 0x01, 0xf7, 0x25, 0x1a, 0x6d, 0xd0, 0x43, 0x44, 0x2f, 0x70, 0x7c,
	0x9f, 0xf9, 0xc3, 0xbe, 0x40, 0x4c, 0xc6, 0x78, 0x06, 0x05, 0xe6, 0x2b, 0x14, 0xe7, 0x8e, 0x8b,
	0xe1, 0x1c, 0xc5, 0x46, 0x31, 0x9e, 0xa3, 0xeb, 0xa8, 0x11, 0xfd, 0x55, 0x35, 0xee, 0xc1, 0xdd,
	0x14, 0x9a, 0x58, 0xa3, 0x03, 0xa4, 0x8b, 0xe2, 0x9c, 0x8b, 0x49, 0xb3, 0x4d, 0xfb, 0x09, 0x7b,
	0x09, 0x32, 0xcc, 0x0b, 0x69, 0x0b, 0x34, 0xc3, 0xbc, 0x79, 0xb5, 0xcc, 0xad, 0x6a, 0xdf, 0x32,
	0xb0, 0x3d, 0xc7, 0x18, 0x09, 0x2d, 0x50, 0xbe, 0x85, 0x9c, 0x54, 0x8e, 0x8a, 0xe8, 0x4a, 0x8d,
	0xe7, 0xe6, 0x35, 0xcf, 0xcc, 0x14, 0x02, 0x73, 0x1a, 0xf4, 0xa6, 0x1d, 0x34, 0x6a, 0x24, 0x7b,
	0x50, 0xc2, 0xb1, 0x13, 0x48, 0xf4, 0xce, 0x02, 0x14, 0x8c, 0x7b, 0x7a, 0xb6, 0xaa, 0xd5, 0xb2,
	0x74, 0x33, 0xce, 0x76, 0xc3, 0xe4, 0xd4, 0x81, 0xc0, 0x51, 0x0a, 0x85, 0xaf, 0xaf, 0x56, 0xb5,
	0xda, 0x06, 0x4d, 0x42, 0xb2, 0x03, 0x79, 0x14, 0x82, 0x0b, 0xa9, 0xe7, 0xc2, 0xc6, 0x38, 0x22,
	0x8f, 0x61, 0x53, 0xa0, 0x8b, 0xec, 0x12, 0xbd, 0xb3, 0x01, 0x53, 0x52, 0xcf, 0x87, 0xe5, 0x8d,
	0x24, 0xd9, 0x64, 0x4a, 0x1a, 0x16, 0x14, 0x66, 0x13, 0x91, 0x22, 0xac, 0x9d, 0xd8, 0x1f, 0xec,
	0xce, 0xa9, 0x5d, 0x5e, 0x21, 0x1b, 0xb0, 0xde, 0x3a, 0xee, 0x1d, 0x36, 0xad, 0x76, 0xab, 0xac,
	0x4d, 0x4b, 0xf4, 0xc4, 0xb6, 0x8f, 0xed, 0xf7, 0xe5, 0xcc, 0xb4, 0x74, 0xd4, 0xf9, 0xd8, 0xb5,
	0xda, 0xfd, 0x76, 0x39, 0x4b, 0x0a, 0x90, 0x6b, 0x53, 0xda, 0xa1, 0xe5, 0x55, 0xe3, 0x5d, 0xec,
	0x91, 0x65, 0xb5, 0xba, 0xc7, 0xc9, 0x5b, 0xfe, 0x83, 0xd7, 0xf7, 0xa1, 0x92, 0xc6, 0x13, 0x9b,
	0xfd, 0x15, 0xfe, 0xeb, 0xa1, 0xef, 0x9d, 0x3a, 0x9f, 0xb1, 0xe3, 0x5b, 0x87, 0xf6, 0xdf, 0x0b,
	0xdc, 0xbc, 0xcf, 0x64, 0x17, 0x8a, 0x13, 0xc7, 0x3d, 0x4b, 0xaa, 0xd9, 0xf0, 0xad, 0x61, 0xe2,
	0xb8, 0x87, 0xf1, 0xc2, 0xdf, 0x81, 0xff, 0x7f, 0x53, 0x8f, 0xc6, 0x6a, 0xfc, 0xc8, 0x42, 0xde,
	0x0a, 0x8d, 0x27, 0x12, 0x76, 0xd2, 0x8f, 0x82, 0xcc, 0x2f, 0xc8, 0xad, 0x37, 0x5a, 0x79, 0xf1,
	0x47, 0xd8, 0xf8, 0x51, 0x56, 0x88, 0x07, 0x5b, 0x0b, 0x07, 0x42, 0xf6, 0x16, 0x39, 0x52, 0xee,
	0xb0, 0xf2, 0x64, 0x19, 0x6c, 0xa6, 0xd2, 0x87, 0xe2, 0xb5, 0xb5, 0x26, 0xbb, 0x37, 0x2f, 0x7c,
	0xc4, 0x5c, 0x5d, 0x76, 0x11, 0xc6, 0xca, 0xbe, 0x46, 0x86, 0x40, 0x16, 0x0d, 0x27, 0x29, 0x53,
	0xa5, 0x6d, 0x56, 0xe5, 0xe9, 0x52, 0xdc, 0x6c, 0xfc, 0x4f, 0xb0, 0x39, 0xe7, 0x1e, 0x79, 0x34,
	0xd7, 0x9b, 0xb6, 0x57, 0x15, 0xe3, 0x36, 0x48, 0xc2, 0xdc, 0x5c, 0xff, 0xfe, 0x26, 0xb7, 0x6f,
	0xbe, 0x36, 0xf7, 0x07, 0xf9, 0xf0, 0xb3, 0x79, 0xf0, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x75,
	0x98, 0x1a, 0xd5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Layer2Client is the client API for Layer2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Layer2Client interface {
	// ClearNeighborDiscovery will clear either a specific neighbor entry or
	// clear the entire table based on parameters provided.
	// TODO: This method is subject to deprecation once OpenConfig models this
	// state.
	ClearNeighborDiscovery(ctx context.Context, in *ClearNeighborDiscoveryRequest, opts ...grpc.CallOption) (*ClearNeighborDiscoveryResponse, error)
	// ClearSpanningTree will reset a blocked spanning tree interface.
	// TODO: This method is subject to deprecation once OpenConfig models this
	// state.
	ClearSpanningTree(ctx context.Context, in *ClearSpanningTreeRequest, opts ...grpc.CallOption) (*ClearSpanningTreeResponse, error)
	// PerformBERT will perform a BERT operation on a port. The stream will
	// return the current state of the operation as well as the ID for the
	// operation.
	PerformBERT(ctx context.Context, in *PerformBERTRequest, opts ...grpc.CallOption) (Layer2_PerformBERTClient, error)
	// ClearLLDPInterface will clear all LLDP adjacencies on the provided
	// interface.
	ClearLLDPInterface(ctx context.Context, in *ClearLLDPInterfaceRequest, opts ...grpc.CallOption) (*ClearLLDPInterfaceResponse, error)
	// SendWakeOnLAN will send a WOL event on the requested interface.
	SendWakeOnLAN(ctx context.Context, in *SendWakeOnLANRequest, opts ...grpc.CallOption) (*SendWakeOnLANResponse, error)
}

type layer2Client struct {
	cc *grpc.ClientConn
}

func NewLayer2Client(cc *grpc.ClientConn) Layer2Client {
	return &layer2Client{cc}
}

func (c *layer2Client) ClearNeighborDiscovery(ctx context.Context, in *ClearNeighborDiscoveryRequest, opts ...grpc.CallOption) (*ClearNeighborDiscoveryResponse, error) {
	out := new(ClearNeighborDiscoveryResponse)
	err := c.cc.Invoke(ctx, "/gnoi.layer2.Layer2/ClearNeighborDiscovery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layer2Client) ClearSpanningTree(ctx context.Context, in *ClearSpanningTreeRequest, opts ...grpc.CallOption) (*ClearSpanningTreeResponse, error) {
	out := new(ClearSpanningTreeResponse)
	err := c.cc.Invoke(ctx, "/gnoi.layer2.Layer2/ClearSpanningTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layer2Client) PerformBERT(ctx context.Context, in *PerformBERTRequest, opts ...grpc.CallOption) (Layer2_PerformBERTClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Layer2_serviceDesc.Streams[0], "/gnoi.layer2.Layer2/PerformBERT", opts...)
	if err != nil {
		return nil, err
	}
	x := &layer2PerformBERTClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Layer2_PerformBERTClient interface {
	Recv() (*PerformBERTResponse, error)
	grpc.ClientStream
}

type layer2PerformBERTClient struct {
	grpc.ClientStream
}

func (x *layer2PerformBERTClient) Recv() (*PerformBERTResponse, error) {
	m := new(PerformBERTResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *layer2Client) ClearLLDPInterface(ctx context.Context, in *ClearLLDPInterfaceRequest, opts ...grpc.CallOption) (*ClearLLDPInterfaceResponse, error) {
	out := new(ClearLLDPInterfaceResponse)
	err := c.cc.Invoke(ctx, "/gnoi.layer2.Layer2/ClearLLDPInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layer2Client) SendWakeOnLAN(ctx context.Context, in *SendWakeOnLANRequest, opts ...grpc.CallOption) (*SendWakeOnLANResponse, error) {
	out := new(SendWakeOnLANResponse)
	err := c.cc.Invoke(ctx, "/gnoi.layer2.Layer2/SendWakeOnLAN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Layer2Server is the server API for Layer2 service.
type Layer2Server interface {
	// ClearNeighborDiscovery will clear either a specific neighbor entry or
	// clear the entire table based on parameters provided.
	// TODO: This method is subject to deprecation once OpenConfig models this
	// state.
	ClearNeighborDiscovery(context.Context, *ClearNeighborDiscoveryRequest) (*ClearNeighborDiscoveryResponse, error)
	// ClearSpanningTree will reset a blocked spanning tree interface.
	// TODO: This method is subject to deprecation once OpenConfig models this
	// state.
	ClearSpanningTree(context.Context, *ClearSpanningTreeRequest) (*ClearSpanningTreeResponse, error)
	// PerformBERT will perform a BERT operation on a port. The stream will
	// return the current state of the operation as well as the ID for the
	// operation.
	PerformBERT(*PerformBERTRequest, Layer2_PerformBERTServer) error
	// ClearLLDPInterface will clear all LLDP adjacencies on the provided
	// interface.
	ClearLLDPInterface(context.Context, *ClearLLDPInterfaceRequest) (*ClearLLDPInterfaceResponse, error)
	// SendWakeOnLAN will send a WOL event on the requested interface.
	SendWakeOnLAN(context.Context, *SendWakeOnLANRequest) (*SendWakeOnLANResponse, error)
}

func RegisterLayer2Server(s *grpc.Server, srv Layer2Server) {
	s.RegisterService(&_Layer2_serviceDesc, srv)
}

func _Layer2_ClearNeighborDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearNeighborDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Layer2Server).ClearNeighborDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.layer2.Layer2/ClearNeighborDiscovery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Layer2Server).ClearNeighborDiscovery(ctx, req.(*ClearNeighborDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Layer2_ClearSpanningTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSpanningTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Layer2Server).ClearSpanningTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.layer2.Layer2/ClearSpanningTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Layer2Server).ClearSpanningTree(ctx, req.(*ClearSpanningTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Layer2_PerformBERT_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PerformBERTRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Layer2Server).PerformBERT(m, &layer2PerformBERTServer{stream})
}

type Layer2_PerformBERTServer interface {
	Send(*PerformBERTResponse) error
	grpc.ServerStream
}

type layer2PerformBERTServer struct {
	grpc.ServerStream
}

func (x *layer2PerformBERTServer) Send(m *PerformBERTResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Layer2_ClearLLDPInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearLLDPInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Layer2Server).ClearLLDPInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.layer2.Layer2/ClearLLDPInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Layer2Server).ClearLLDPInterface(ctx, req.(*ClearLLDPInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Layer2_SendWakeOnLAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWakeOnLANRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Layer2Server).SendWakeOnLAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.layer2.Layer2/SendWakeOnLAN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Layer2Server).SendWakeOnLAN(ctx, req.(*SendWakeOnLANRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Layer2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.layer2.Layer2",
	HandlerType: (*Layer2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearNeighborDiscovery",
			Handler:    _Layer2_ClearNeighborDiscovery_Handler,
		},
		{
			MethodName: "ClearSpanningTree",
			Handler:    _Layer2_ClearSpanningTree_Handler,
		},
		{
			MethodName: "ClearLLDPInterface",
			Handler:    _Layer2_ClearLLDPInterface_Handler,
		},
		{
			MethodName: "SendWakeOnLAN",
			Handler:    _Layer2_SendWakeOnLAN_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PerformBERT",
			Handler:       _Layer2_PerformBERT_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "layer2/layer2.proto",
}
